// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LoliaFrpClient.Api.User.Traffic.Charges
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChargesGetResponse_data_charges : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>实际扣费量（字节）</summary>
        public int? Charged { get; set; }
        /// <summary>节点 ID（字符串）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeId { get; set; }
#nullable restore
#else
        public string NodeId { get; set; }
#endif
        /// <summary>节点名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeName { get; set; }
#nullable restore
#else
        public string NodeName { get; set; }
#endif
        /// <summary>隧道备注</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remark { get; set; }
#nullable restore
#else
        public string Remark { get; set; }
#endif
        /// <summary>扣费时间（RFC3339）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Time { get; set; }
#nullable restore
#else
        public string Time { get; set; }
#endif
        /// <summary>原始入站增量（字节）</summary>
        public int? TrafficIn { get; set; }
        /// <summary>原始出站增量（字节）</summary>
        public int? TrafficOut { get; set; }
        /// <summary>扣费时的节点流量倍率</summary>
        public double? TrafficRatio { get; set; }
        /// <summary>原始流量合计（字节）</summary>
        public int? TrafficTotal { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.User.Traffic.Charges.ChargesGetResponse_data_charges"/> and sets the default values.
        /// </summary>
        public ChargesGetResponse_data_charges()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Traffic.Charges.ChargesGetResponse_data_charges"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LoliaFrpClient.Api.User.Traffic.Charges.ChargesGetResponse_data_charges CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LoliaFrpClient.Api.User.Traffic.Charges.ChargesGetResponse_data_charges();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "charged", n => { Charged = n.GetIntValue(); } },
                { "node_id", n => { NodeId = n.GetStringValue(); } },
                { "node_name", n => { NodeName = n.GetStringValue(); } },
                { "remark", n => { Remark = n.GetStringValue(); } },
                { "time", n => { Time = n.GetStringValue(); } },
                { "traffic_in", n => { TrafficIn = n.GetIntValue(); } },
                { "traffic_out", n => { TrafficOut = n.GetIntValue(); } },
                { "traffic_ratio", n => { TrafficRatio = n.GetDoubleValue(); } },
                { "traffic_total", n => { TrafficTotal = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("charged", Charged);
            writer.WriteStringValue("node_id", NodeId);
            writer.WriteStringValue("node_name", NodeName);
            writer.WriteStringValue("remark", Remark);
            writer.WriteStringValue("time", Time);
            writer.WriteIntValue("traffic_in", TrafficIn);
            writer.WriteIntValue("traffic_out", TrafficOut);
            writer.WriteDoubleValue("traffic_ratio", TrafficRatio);
            writer.WriteIntValue("traffic_total", TrafficTotal);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
