// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Api.Kyc.Callback
{
    /// <summary>
    /// Builds and executes requests for operations under \kyc\callback
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CallbackRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Kyc.Callback.CallbackRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CallbackRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/kyc/callback{?order_no*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Kyc.Callback.CallbackRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CallbackRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/kyc/callback{?order_no*}", rawUrl)
        {
        }
        /// <summary>
        /// 支付宝实名认证完成后的回调地址（由 /user/kyc/init 生成并传给支付宝，无需鉴权）。根据 order_no 向支付宝查询认证结果，若通过（Passed=T）则将记录状态更新为 success。无论结果如何，最终都以 302 重定向到 https://dash.lolia.link，不返回 JSON。**鉴权**：无需鉴权**错误响应**：| code | msg || --- | --- || 302 | 始终 302 重定向到 https://dash.lolia.link（无 JSON 响应体） |
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.Kyc.Callback.CallbackRequestBuilder.CallbackRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.Kyc.Callback.CallbackRequestBuilder.CallbackRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 支付宝实名认证完成后的回调地址（由 /user/kyc/init 生成并传给支付宝，无需鉴权）。根据 order_no 向支付宝查询认证结果，若通过（Passed=T）则将记录状态更新为 success。无论结果如何，最终都以 302 重定向到 https://dash.lolia.link，不返回 JSON。**鉴权**：无需鉴权**错误响应**：| code | msg || --- | --- || 302 | 始终 302 重定向到 https://dash.lolia.link（无 JSON 响应体） |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Api.Kyc.Callback.CallbackRequestBuilder.CallbackRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Api.Kyc.Callback.CallbackRequestBuilder.CallbackRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/octet-stream");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Kyc.Callback.CallbackRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Api.Kyc.Callback.CallbackRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Api.Kyc.Callback.CallbackRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 支付宝实名认证完成后的回调地址（由 /user/kyc/init 生成并传给支付宝，无需鉴权）。根据 order_no 向支付宝查询认证结果，若通过（Passed=T）则将记录状态更新为 success。无论结果如何，最终都以 302 重定向到 https://dash.lolia.link，不返回 JSON。**鉴权**：无需鉴权**错误响应**：| code | msg || --- | --- || 302 | 始终 302 重定向到 https://dash.lolia.link（无 JSON 响应体） |
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CallbackRequestBuilderGetQueryParameters 
        {
            /// <summary>KYC 订单号；为空、不存在或查询失败时直接 302 跳转</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order_no")]
            public string? OrderNo { get; set; }
#nullable restore
#else
            [QueryParameter("order_no")]
            public string OrderNo { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CallbackRequestBuilderGetRequestConfiguration : RequestConfiguration<global::LoliaFrpClient.Api.Kyc.Callback.CallbackRequestBuilder.CallbackRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
