// <auto-generated/>
#pragma warning disable CS0618
using LoliaFrpClient.Api.Admin.Nodes.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Api.Admin.Nodes
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\nodes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NodesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LoliaFrpClient.Api.admin.nodes.item collection</summary>
        /// <param name="position">节点ID</param>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Admin.Nodes.Item.WithNode_ItemRequestBuilder"/></returns>
        public global::LoliaFrpClient.Api.Admin.Nodes.Item.WithNode_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("node_id", position);
                return new global::LoliaFrpClient.Api.Admin.Nodes.Item.WithNode_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the LoliaFrpClient.Api.admin.nodes.item collection</summary>
        /// <param name="position">节点ID</param>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Admin.Nodes.Item.WithNode_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::LoliaFrpClient.Api.Admin.Nodes.Item.WithNode_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("node_id", position);
                return new global::LoliaFrpClient.Api.Admin.Nodes.Item.WithNode_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NodesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/nodes{?keyword*,limit*,page*,sort*,status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NodesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/nodes{?keyword*,limit*,page*,sort*,status*}", rawUrl)
        {
        }
        /// <summary>
        /// 分页获取节点列表（不含软删除节点），附带系统信息快照、隧道计数与负载评分。默认排序：online &gt; authenticated &gt; 其他，再按创建时间倒序。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 500 | 获取节点列表失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Admin.Nodes.NodesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.Admin.Nodes.NodesGetResponse?> GetAsNodesGetResponseAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder.NodesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.Admin.Nodes.NodesGetResponse> GetAsNodesGetResponseAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder.NodesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Api.Admin.Nodes.Nodes401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.Admin.Nodes.Nodes403Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.Admin.Nodes.Nodes500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.Admin.Nodes.NodesGetResponse>(requestInfo, global::LoliaFrpClient.Api.Admin.Nodes.NodesGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 分页获取节点列表（不含软删除节点），附带系统信息快照、隧道计数与负载评分。默认排序：online &gt; authenticated &gt; 其他，再按创建时间倒序。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 500 | 获取节点列表失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Admin.Nodes.NodesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsNodesGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.Admin.Nodes.NodesResponse?> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder.NodesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.Admin.Nodes.NodesResponse> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder.NodesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Api.Admin.Nodes.Nodes401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.Admin.Nodes.Nodes403Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.Admin.Nodes.Nodes500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.Admin.Nodes.NodesResponse>(requestInfo, global::LoliaFrpClient.Api.Admin.Nodes.NodesResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 管理员添加节点。成功返回 HTTP 201，新节点初始状态为 offline；响应中的 token 为节点连接密钥（32 位随机字母），仅在创建时返回一次，请妥善保存。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 请求参数错误: &lt;校验错误详情&gt; || 400 | 节点名称不能为空 || 400 | 节点IP不能为空 || 400 | 可用端口格式错误: 无效的端口范围: &lt;item&gt; || 400 | 支持的协议不能为空 || 409 | 节点名称已存在 || 500 | 创建节点失败 || 500 | 生成节点Token失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Admin.Nodes.NodesPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.Admin.Nodes.NodesPostResponse?> PostAsNodesPostResponseAsync(global::LoliaFrpClient.Api.Admin.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.Admin.Nodes.NodesPostResponse> PostAsNodesPostResponseAsync(global::LoliaFrpClient.Api.Admin.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Api.Admin.Nodes.Nodes400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Api.Admin.Nodes.Nodes401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.Admin.Nodes.Nodes403Error.CreateFromDiscriminatorValue },
                { "409", global::LoliaFrpClient.Api.Admin.Nodes.Nodes409Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.Admin.Nodes.Nodes500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.Admin.Nodes.NodesPostResponse>(requestInfo, global::LoliaFrpClient.Api.Admin.Nodes.NodesPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 管理员添加节点。成功返回 HTTP 201，新节点初始状态为 offline；响应中的 token 为节点连接密钥（32 位随机字母），仅在创建时返回一次，请妥善保存。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 请求参数错误: &lt;校验错误详情&gt; || 400 | 节点名称不能为空 || 400 | 节点IP不能为空 || 400 | 可用端口格式错误: 无效的端口范围: &lt;item&gt; || 400 | 支持的协议不能为空 || 409 | 节点名称已存在 || 500 | 创建节点失败 || 500 | 生成节点Token失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Admin.Nodes.NodesResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Nodes.Nodes500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsNodesPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.Admin.Nodes.NodesResponse?> PostAsync(global::LoliaFrpClient.Api.Admin.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.Admin.Nodes.NodesResponse> PostAsync(global::LoliaFrpClient.Api.Admin.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Api.Admin.Nodes.Nodes400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Api.Admin.Nodes.Nodes401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.Admin.Nodes.Nodes403Error.CreateFromDiscriminatorValue },
                { "409", global::LoliaFrpClient.Api.Admin.Nodes.Nodes409Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.Admin.Nodes.Nodes500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.Admin.Nodes.NodesResponse>(requestInfo, global::LoliaFrpClient.Api.Admin.Nodes.NodesResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 分页获取节点列表（不含软删除节点），附带系统信息快照、隧道计数与负载评分。默认排序：online &gt; authenticated &gt; 其他，再按创建时间倒序。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 500 | 获取节点列表失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder.NodesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder.NodesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// 管理员添加节点。成功返回 HTTP 201，新节点初始状态为 offline；响应中的 token 为节点连接密钥（32 位随机字母），仅在创建时返回一次，请妥善保存。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 请求参数错误: &lt;校验错误详情&gt; || 400 | 节点名称不能为空 || 400 | 节点IP不能为空 || 400 | 可用端口格式错误: 无效的端口范围: &lt;item&gt; || 400 | 支持的协议不能为空 || 409 | 节点名称已存在 || 500 | 创建节点失败 || 500 | 生成节点Token失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::LoliaFrpClient.Api.Admin.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::LoliaFrpClient.Api.Admin.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 分页获取节点列表（不含软删除节点），附带系统信息快照、隧道计数与负载评分。默认排序：online &gt; authenticated &gt; 其他，再按创建时间倒序。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 500 | 获取节点列表失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NodesRequestBuilderGetQueryParameters 
        {
            /// <summary>关键字，模糊匹配节点ID/名称/地区代码/IP/赞助者名/赞助者用户名/备注</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("keyword")]
            public string? Keyword { get; set; }
#nullable restore
#else
            [QueryParameter("keyword")]
            public string Keyword { get; set; }
#endif
            /// <summary>每页数量，默认 20，小于 1 时按 20 处理，最大 200</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>页码，默认 1，小于 1 时按 1 处理</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>排序：load_desc / load_asc（按网络收发速率之和）/ cpu_desc / memory_desc / updated_desc / updated_asc；其他值使用默认排序</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            /// <summary>按状态筛选：online / authenticated / offline；空或 all 表示不筛选</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NodesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::LoliaFrpClient.Api.Admin.Nodes.NodesRequestBuilder.NodesRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NodesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
