// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LoliaFrpClient.Api.Admin.Nodes
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NodesGetResponse_data_items : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>节点 agent 版本</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgentVersion { get; set; }
#nullable restore
#else
        public string AgentVersion { get; set; }
#endif
        /// <summary>可用端口列表，如 [&quot;10000-20000&quot;,&quot;8080&quot;]</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AvailablePorts { get; set; }
#nullable restore
#else
        public List<string> AvailablePorts { get; set; }
#endif
        /// <summary>节点带宽（Mbps）</summary>
        public int? Bandwidth { get; set; }
        /// <summary>带宽占用率（%，取收发较大值 / bandwidth，0-100）</summary>
        public double? BandwidthUsagePercent { get; set; }
        /// <summary>是否需要备案</summary>
        public bool? BeianRequired { get; set; }
        /// <summary>已建立 TCP 连接数</summary>
        public int? ConnTcpEstablished { get; set; }
        /// <summary>TCP 连接总数</summary>
        public int? ConnTcpTotal { get; set; }
        /// <summary>国家代码（大写，如 CN）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryCode { get; set; }
#nullable restore
#else
        public string CountryCode { get; set; }
#endif
        /// <summary>CPU 核数</summary>
        public int? CpuCores { get; set; }
        /// <summary>CPU 使用率（%，保留两位小数）</summary>
        public double? CpuUsagePercent { get; set; }
        /// <summary>创建时间（RFC3339）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>frps 服务端口</summary>
        public int? FrpsPort { get; set; }
        /// <summary>frps 版本</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FrpsVersion { get; set; }
#nullable restore
#else
        public string FrpsVersion { get; set; }
#endif
        /// <summary>是否高流量节点</summary>
        public bool? HighTraffic { get; set; }
        /// <summary>节点ID</summary>
        public int? Id { get; set; }
        /// <summary>节点地址（IP 或域名）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IpAddress { get; set; }
#nullable restore
#else
        public string IpAddress { get; set; }
#endif
        /// <summary>最后在线时间（RFC3339），可能为 null</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastSeen { get; set; }
#nullable restore
#else
        public string LastSeen { get; set; }
#endif
        /// <summary>综合负载评分（%，带宽/CPU/内存/连接加权），节点未上报系统信息时为 null</summary>
        public double? Load { get; set; }
        /// <summary>可用内存（字节）</summary>
        public long? MemoryAvailableBytes { get; set; }
        /// <summary>内存总量（字节）</summary>
        public long? MemoryTotalBytes { get; set; }
        /// <summary>已用内存（字节）</summary>
        public long? MemoryUsedBytes { get; set; }
        /// <summary>内存使用率（%）</summary>
        public double? MemoryUsedPercent { get; set; }
        /// <summary>节点名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>是否需要实名认证</summary>
        public bool? NeedKyc { get; set; }
        /// <summary>累计接收字节</summary>
        public long? NetworkRxBytes { get; set; }
        /// <summary>接收速率（字节/秒）</summary>
        public double? NetworkRxRateBytesSec { get; set; }
        /// <summary>接收速率（Mbps）</summary>
        public double? NetworkRxRateMbps { get; set; }
        /// <summary>累计发送字节</summary>
        public long? NetworkTxBytes { get; set; }
        /// <summary>发送速率（字节/秒）</summary>
        public double? NetworkTxRateBytesSec { get; set; }
        /// <summary>发送速率（Mbps）</summary>
        public double? NetworkTxRateMbps { get; set; }
        /// <summary>该节点在线隧道数</summary>
        public int? OnlineTunnelCount { get; set; }
        /// <summary>地区代码</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegionCode { get; set; }
#nullable restore
#else
        public string RegionCode { get; set; }
#endif
        /// <summary>备注</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remark { get; set; }
#nullable restore
#else
        public string Remark { get; set; }
#endif
        /// <summary>系统信息最近上报时间，未上报为 null</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReportedAt { get; set; }
#nullable restore
#else
        public string ReportedAt { get; set; }
#endif
        /// <summary>赞助者展示名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sponsor { get; set; }
#nullable restore
#else
        public string Sponsor { get; set; }
#endif
        /// <summary>绑定的赞助者用户ID，未绑定为 null</summary>
        public int? SponsorUserId { get; set; }
        /// <summary>赞助者用户名，未绑定为空字符串</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SponsorUsername { get; set; }
#nullable restore
#else
        public string SponsorUsername { get; set; }
#endif
        /// <summary>节点状态：online / authenticated / offline</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>支持的协议列表（tcp/udp/http）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SupportedProtocols { get; set; }
#nullable restore
#else
        public List<string> SupportedProtocols { get; set; }
#endif
        /// <summary>该节点隧道总数（不含软删除）</summary>
        public int? TotalTunnelCount { get; set; }
        /// <summary>流量计费倍率</summary>
        public double? TrafficRatio { get; set; }
        /// <summary>更新时间（RFC3339）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Admin.Nodes.NodesGetResponse_data_items"/> and sets the default values.
        /// </summary>
        public NodesGetResponse_data_items()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Admin.Nodes.NodesGetResponse_data_items"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LoliaFrpClient.Api.Admin.Nodes.NodesGetResponse_data_items CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LoliaFrpClient.Api.Admin.Nodes.NodesGetResponse_data_items();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_version", n => { AgentVersion = n.GetStringValue(); } },
                { "available_ports", n => { AvailablePorts = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "bandwidth", n => { Bandwidth = n.GetIntValue(); } },
                { "bandwidth_usage_percent", n => { BandwidthUsagePercent = n.GetDoubleValue(); } },
                { "beian_required", n => { BeianRequired = n.GetBoolValue(); } },
                { "conn_tcp_established", n => { ConnTcpEstablished = n.GetIntValue(); } },
                { "conn_tcp_total", n => { ConnTcpTotal = n.GetIntValue(); } },
                { "country_code", n => { CountryCode = n.GetStringValue(); } },
                { "cpu_cores", n => { CpuCores = n.GetIntValue(); } },
                { "cpu_usage_percent", n => { CpuUsagePercent = n.GetDoubleValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "frps_port", n => { FrpsPort = n.GetIntValue(); } },
                { "frps_version", n => { FrpsVersion = n.GetStringValue(); } },
                { "high_traffic", n => { HighTraffic = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "ip_address", n => { IpAddress = n.GetStringValue(); } },
                { "last_seen", n => { LastSeen = n.GetStringValue(); } },
                { "load", n => { Load = n.GetDoubleValue(); } },
                { "memory_available_bytes", n => { MemoryAvailableBytes = n.GetLongValue(); } },
                { "memory_total_bytes", n => { MemoryTotalBytes = n.GetLongValue(); } },
                { "memory_used_bytes", n => { MemoryUsedBytes = n.GetLongValue(); } },
                { "memory_used_percent", n => { MemoryUsedPercent = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "need_kyc", n => { NeedKyc = n.GetBoolValue(); } },
                { "network_rx_bytes", n => { NetworkRxBytes = n.GetLongValue(); } },
                { "network_rx_rate_bytes_sec", n => { NetworkRxRateBytesSec = n.GetDoubleValue(); } },
                { "network_rx_rate_mbps", n => { NetworkRxRateMbps = n.GetDoubleValue(); } },
                { "network_tx_bytes", n => { NetworkTxBytes = n.GetLongValue(); } },
                { "network_tx_rate_bytes_sec", n => { NetworkTxRateBytesSec = n.GetDoubleValue(); } },
                { "network_tx_rate_mbps", n => { NetworkTxRateMbps = n.GetDoubleValue(); } },
                { "online_tunnel_count", n => { OnlineTunnelCount = n.GetIntValue(); } },
                { "region_code", n => { RegionCode = n.GetStringValue(); } },
                { "remark", n => { Remark = n.GetStringValue(); } },
                { "reported_at", n => { ReportedAt = n.GetStringValue(); } },
                { "sponsor", n => { Sponsor = n.GetStringValue(); } },
                { "sponsor_user_id", n => { SponsorUserId = n.GetIntValue(); } },
                { "sponsor_username", n => { SponsorUsername = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "supported_protocols", n => { SupportedProtocols = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "total_tunnel_count", n => { TotalTunnelCount = n.GetIntValue(); } },
                { "traffic_ratio", n => { TrafficRatio = n.GetDoubleValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("agent_version", AgentVersion);
            writer.WriteCollectionOfPrimitiveValues<string>("available_ports", AvailablePorts);
            writer.WriteIntValue("bandwidth", Bandwidth);
            writer.WriteDoubleValue("bandwidth_usage_percent", BandwidthUsagePercent);
            writer.WriteBoolValue("beian_required", BeianRequired);
            writer.WriteIntValue("conn_tcp_established", ConnTcpEstablished);
            writer.WriteIntValue("conn_tcp_total", ConnTcpTotal);
            writer.WriteStringValue("country_code", CountryCode);
            writer.WriteIntValue("cpu_cores", CpuCores);
            writer.WriteDoubleValue("cpu_usage_percent", CpuUsagePercent);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteIntValue("frps_port", FrpsPort);
            writer.WriteStringValue("frps_version", FrpsVersion);
            writer.WriteBoolValue("high_traffic", HighTraffic);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("ip_address", IpAddress);
            writer.WriteStringValue("last_seen", LastSeen);
            writer.WriteDoubleValue("load", Load);
            writer.WriteLongValue("memory_available_bytes", MemoryAvailableBytes);
            writer.WriteLongValue("memory_total_bytes", MemoryTotalBytes);
            writer.WriteLongValue("memory_used_bytes", MemoryUsedBytes);
            writer.WriteDoubleValue("memory_used_percent", MemoryUsedPercent);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("need_kyc", NeedKyc);
            writer.WriteLongValue("network_rx_bytes", NetworkRxBytes);
            writer.WriteDoubleValue("network_rx_rate_bytes_sec", NetworkRxRateBytesSec);
            writer.WriteDoubleValue("network_rx_rate_mbps", NetworkRxRateMbps);
            writer.WriteLongValue("network_tx_bytes", NetworkTxBytes);
            writer.WriteDoubleValue("network_tx_rate_bytes_sec", NetworkTxRateBytesSec);
            writer.WriteDoubleValue("network_tx_rate_mbps", NetworkTxRateMbps);
            writer.WriteIntValue("online_tunnel_count", OnlineTunnelCount);
            writer.WriteStringValue("region_code", RegionCode);
            writer.WriteStringValue("remark", Remark);
            writer.WriteStringValue("reported_at", ReportedAt);
            writer.WriteStringValue("sponsor", Sponsor);
            writer.WriteIntValue("sponsor_user_id", SponsorUserId);
            writer.WriteStringValue("sponsor_username", SponsorUsername);
            writer.WriteStringValue("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("supported_protocols", SupportedProtocols);
            writer.WriteIntValue("total_tunnel_count", TotalTunnelCount);
            writer.WriteDoubleValue("traffic_ratio", TrafficRatio);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
