// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\tunnel\{tunnel_id}\traffic\daily
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DailyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DailyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/tunnel/{tunnel_id}/traffic/daily{?days*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DailyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/tunnel/{tunnel_id}/traffic/daily{?days*}", rawUrl)
        {
        }
        /// <summary>
        /// 查询指定隧道最近 N 天（含今天，最多 7 天）的每日流量，按日期升序补齐（无数据日期流量为 0）。软删除的隧道返回 404。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 隧道ID格式错误 || 404 | 隧道不存在 || 500 | 获取隧道信息失败 || 500 | 获取隧道每日流量统计失败: &lt;错误详情&gt; || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyGetResponse?> GetAsDailyGetResponseAsync(Action<RequestConfiguration<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder.DailyRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyGetResponse> GetAsDailyGetResponseAsync(Action<RequestConfiguration<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder.DailyRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyGetResponse>(requestInfo, global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 查询指定隧道最近 N 天（含今天，最多 7 天）的每日流量，按日期升序补齐（无数据日期流量为 0）。软删除的隧道返回 404。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 隧道ID格式错误 || 404 | 隧道不存在 || 500 | 获取隧道信息失败 || 500 | 获取隧道每日流量统计失败: &lt;错误详情&gt; || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsDailyGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyResponse?> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder.DailyRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyResponse> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder.DailyRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.Daily500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyResponse>(requestInfo, global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 查询指定隧道最近 N 天（含今天，最多 7 天）的每日流量，按日期升序补齐（无数据日期流量为 0）。软删除的隧道返回 404。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 隧道ID格式错误 || 404 | 隧道不存在 || 500 | 获取隧道信息失败 || 500 | 获取隧道每日流量统计失败: &lt;错误详情&gt; || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder.DailyRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder.DailyRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 查询指定隧道最近 N 天（含今天，最多 7 天）的每日流量，按日期升序补齐（无数据日期流量为 0）。软删除的隧道返回 404。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 隧道ID格式错误 || 404 | 隧道不存在 || 500 | 获取隧道信息失败 || 500 | 获取隧道每日流量统计失败: &lt;错误详情&gt; || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DailyRequestBuilderGetQueryParameters 
        {
            /// <summary>统计天数，默认 7，范围 1-7（小于 1 按 7，大于 7 按 7）；返回的每日数组始终补齐为 days 条，无数据的日期流量为 0</summary>
            [QueryParameter("days")]
            public int? Days { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DailyRequestBuilderGetRequestConfiguration : RequestConfiguration<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Traffic.Daily.DailyRequestBuilder.DailyRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
