// <auto-generated/>
#pragma warning disable CS0618
using LoliaFrpClient.Api.User.Tunnel.Item;
using LoliaFrpClient.Api.User.Tunnel.Token;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Api.User.Tunnel
{
    /// <summary>
    /// Builds and executes requests for operations under \user\tunnel
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TunnelRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The token property</summary>
        public global::LoliaFrpClient.Api.User.Tunnel.Token.TokenRequestBuilder Token
        {
            get => new global::LoliaFrpClient.Api.User.Tunnel.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the LoliaFrpClient.Api.user.tunnel.item collection</summary>
        /// <param name="position">隧道名称</param>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Tunnel.Item.WithTunnel_nameItemRequestBuilder"/></returns>
        public global::LoliaFrpClient.Api.User.Tunnel.Item.WithTunnel_nameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tunnel_name", position);
                return new global::LoliaFrpClient.Api.User.Tunnel.Item.WithTunnel_nameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TunnelRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/tunnel{?center*,limit*,page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TunnelRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/tunnel{?center*,limit*,page*}", rawUrl)
        {
        }
        /// <summary>
        /// 分页获取当前用户的隧道列表。可通过 center=true 为每条记录附带节点所在地区的地图中心坐标 node_center。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `tunnel:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: tunnel:read || 500 | 获取隧道列表失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Tunnel.TunnelGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.User.Tunnel.TunnelGetResponse?> GetAsTunnelGetResponseAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder.TunnelRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.User.Tunnel.TunnelGetResponse> GetAsTunnelGetResponseAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder.TunnelRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Api.User.Tunnel.Tunnel401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.User.Tunnel.Tunnel403Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.User.Tunnel.Tunnel500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.User.Tunnel.TunnelGetResponse>(requestInfo, global::LoliaFrpClient.Api.User.Tunnel.TunnelGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 分页获取当前用户的隧道列表。可通过 center=true 为每条记录附带节点所在地区的地图中心坐标 node_center。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `tunnel:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: tunnel:read || 500 | 获取隧道列表失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Tunnel.TunnelResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsTunnelGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.User.Tunnel.TunnelResponse?> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder.TunnelRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.User.Tunnel.TunnelResponse> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder.TunnelRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Api.User.Tunnel.Tunnel401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.User.Tunnel.Tunnel403Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.User.Tunnel.Tunnel500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.User.Tunnel.TunnelResponse>(requestInfo, global::LoliaFrpClient.Api.User.Tunnel.TunnelResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 创建隧道，成功返回 HTTP 201。隧道名称由服务端随机生成，初始状态 inactive。前置条件/业务规则：账户未封禁；必须已绑定 QQ；隧道数量不能超过用户上限 max_tunnel_count；节点 need_kyc=true 时需已通过实名认证；HTTP/HTTPS 隧道必须提供 custom_domain，且该域名（或其父域名）已在域名白名单中验证通过，不允许泛域名；节点 beian_required=true 时域名还需有 ICP 备案。HTTP/HTTPS 隧道 remote_port 固定为 80（忽略传入值）；TCP/UDP 隧道 remote_port 不传或为 0 时自动分配，指定时必须在节点可用端口范围内且未被占用。创建时不接受 config，auto_tls/高级配置需通过编辑接口设置。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `tunnel:write`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: tunnel:write || 400 | 请求参数错误: &lt;校验错误&gt; || 400 | 节点不存在 || 400 | HTTP/HTTPS 类型的隧道必须配置自定义域名 || 400 | 域名验证失败: 域名未添加到白名单 || 400 | 端口 20001 不在节点的可用端口范围内 || 401 | 用户不存在 || 403 | 账户已被封禁 || 403 | 请先绑定 QQ 后再创建或启动隧道 || 403 | 隧道数量已达到限制(5/5) || 403 | 该节点需要实名认证，请先完成KYC || 403 | 该域名未通过验证或不可用，请先添加并验证域名 || 403 | 该节点需要域名备案，请先完成ICP备案 || 409 | 端口 20001 已被占用 || 409 | 该节点暂无可用端口 || 500 | 创建隧道失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Tunnel.TunnelPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.User.Tunnel.TunnelPostResponse?> PostAsTunnelPostResponseAsync(global::LoliaFrpClient.Api.User.Tunnel.TunnelPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.User.Tunnel.TunnelPostResponse> PostAsTunnelPostResponseAsync(global::LoliaFrpClient.Api.User.Tunnel.TunnelPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Api.User.Tunnel.Tunnel400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Api.User.Tunnel.Tunnel401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.User.Tunnel.Tunnel403Error.CreateFromDiscriminatorValue },
                { "409", global::LoliaFrpClient.Api.User.Tunnel.Tunnel409Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.User.Tunnel.Tunnel500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.User.Tunnel.TunnelPostResponse>(requestInfo, global::LoliaFrpClient.Api.User.Tunnel.TunnelPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 创建隧道，成功返回 HTTP 201。隧道名称由服务端随机生成，初始状态 inactive。前置条件/业务规则：账户未封禁；必须已绑定 QQ；隧道数量不能超过用户上限 max_tunnel_count；节点 need_kyc=true 时需已通过实名认证；HTTP/HTTPS 隧道必须提供 custom_domain，且该域名（或其父域名）已在域名白名单中验证通过，不允许泛域名；节点 beian_required=true 时域名还需有 ICP 备案。HTTP/HTTPS 隧道 remote_port 固定为 80（忽略传入值）；TCP/UDP 隧道 remote_port 不传或为 0 时自动分配，指定时必须在节点可用端口范围内且未被占用。创建时不接受 config，auto_tls/高级配置需通过编辑接口设置。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `tunnel:write`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: tunnel:write || 400 | 请求参数错误: &lt;校验错误&gt; || 400 | 节点不存在 || 400 | HTTP/HTTPS 类型的隧道必须配置自定义域名 || 400 | 域名验证失败: 域名未添加到白名单 || 400 | 端口 20001 不在节点的可用端口范围内 || 401 | 用户不存在 || 403 | 账户已被封禁 || 403 | 请先绑定 QQ 后再创建或启动隧道 || 403 | 隧道数量已达到限制(5/5) || 403 | 该节点需要实名认证，请先完成KYC || 403 | 该域名未通过验证或不可用，请先添加并验证域名 || 403 | 该节点需要域名备案，请先完成ICP备案 || 409 | 端口 20001 已被占用 || 409 | 该节点暂无可用端口 || 500 | 创建隧道失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Tunnel.TunnelResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Tunnel.Tunnel500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsTunnelPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.User.Tunnel.TunnelResponse?> PostAsync(global::LoliaFrpClient.Api.User.Tunnel.TunnelPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.User.Tunnel.TunnelResponse> PostAsync(global::LoliaFrpClient.Api.User.Tunnel.TunnelPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Api.User.Tunnel.Tunnel400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Api.User.Tunnel.Tunnel401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.User.Tunnel.Tunnel403Error.CreateFromDiscriminatorValue },
                { "409", global::LoliaFrpClient.Api.User.Tunnel.Tunnel409Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.User.Tunnel.Tunnel500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.User.Tunnel.TunnelResponse>(requestInfo, global::LoliaFrpClient.Api.User.Tunnel.TunnelResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 分页获取当前用户的隧道列表。可通过 center=true 为每条记录附带节点所在地区的地图中心坐标 node_center。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `tunnel:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: tunnel:read || 500 | 获取隧道列表失败 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder.TunnelRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder.TunnelRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// 创建隧道，成功返回 HTTP 201。隧道名称由服务端随机生成，初始状态 inactive。前置条件/业务规则：账户未封禁；必须已绑定 QQ；隧道数量不能超过用户上限 max_tunnel_count；节点 need_kyc=true 时需已通过实名认证；HTTP/HTTPS 隧道必须提供 custom_domain，且该域名（或其父域名）已在域名白名单中验证通过，不允许泛域名；节点 beian_required=true 时域名还需有 ICP 备案。HTTP/HTTPS 隧道 remote_port 固定为 80（忽略传入值）；TCP/UDP 隧道 remote_port 不传或为 0 时自动分配，指定时必须在节点可用端口范围内且未被占用。创建时不接受 config，auto_tls/高级配置需通过编辑接口设置。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `tunnel:write`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: tunnel:write || 400 | 请求参数错误: &lt;校验错误&gt; || 400 | 节点不存在 || 400 | HTTP/HTTPS 类型的隧道必须配置自定义域名 || 400 | 域名验证失败: 域名未添加到白名单 || 400 | 端口 20001 不在节点的可用端口范围内 || 401 | 用户不存在 || 403 | 账户已被封禁 || 403 | 请先绑定 QQ 后再创建或启动隧道 || 403 | 隧道数量已达到限制(5/5) || 403 | 该节点需要实名认证，请先完成KYC || 403 | 该域名未通过验证或不可用，请先添加并验证域名 || 403 | 该节点需要域名备案，请先完成ICP备案 || 409 | 端口 20001 已被占用 || 409 | 该节点暂无可用端口 || 500 | 创建隧道失败 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::LoliaFrpClient.Api.User.Tunnel.TunnelPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::LoliaFrpClient.Api.User.Tunnel.TunnelPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 分页获取当前用户的隧道列表。可通过 center=true 为每条记录附带节点所在地区的地图中心坐标 node_center。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `tunnel:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: tunnel:read || 500 | 获取隧道列表失败 |
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TunnelRequestBuilderGetQueryParameters 
        {
            /// <summary>是否返回节点地图中心坐标 node_center，默认 false</summary>
            [QueryParameter("center")]
            public bool? Center { get; set; }
            /// <summary>每页数量，默认 10，取值 1-100（超出范围使用默认值 10）</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>页码，默认 1</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TunnelRequestBuilderGetRequestConfiguration : RequestConfiguration<global::LoliaFrpClient.Api.User.Tunnel.TunnelRequestBuilder.TunnelRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TunnelRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
