// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LoliaFrpClient.Api.User.Announcements.Board
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BoardGetResponse_data_items : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>按钮文字，未设置时为空字符串</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionLabel { get; set; }
#nullable restore
#else
        public string ActionLabel { get; set; }
#endif
        /// <summary>按钮链接（http/https），未设置时为空字符串</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionUrl { get; set; }
#nullable restore
#else
        public string ActionUrl { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>内容（最多 5000 字符）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>创建时间（RFC3339）</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>显示位置：top / board</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayType { get; set; }
#nullable restore
#else
        public string DisplayType { get; set; }
#endif
        /// <summary>公告 ID</summary>
        public int? Id { get; set; }
        /// <summary>等级：info / warning / error / success / normal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level { get; set; }
#nullable restore
#else
        public string Level { get; set; }
#endif
        /// <summary>是否需要弹窗展示</summary>
        public bool? NeedModal { get; set; }
        /// <summary>标题（最多 120 字符）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>更新时间（RFC3339）</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.User.Announcements.Board.BoardGetResponse_data_items"/> and sets the default values.
        /// </summary>
        public BoardGetResponse_data_items()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Announcements.Board.BoardGetResponse_data_items"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LoliaFrpClient.Api.User.Announcements.Board.BoardGetResponse_data_items CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LoliaFrpClient.Api.User.Announcements.Board.BoardGetResponse_data_items();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action_label", n => { ActionLabel = n.GetStringValue(); } },
                { "action_url", n => { ActionUrl = n.GetStringValue(); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "display_type", n => { DisplayType = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "level", n => { Level = n.GetStringValue(); } },
                { "need_modal", n => { NeedModal = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action_label", ActionLabel);
            writer.WriteStringValue("action_url", ActionUrl);
            writer.WriteStringValue("content", Content);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("display_type", DisplayType);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("level", Level);
            writer.WriteBoolValue("need_modal", NeedModal);
            writer.WriteStringValue("title", Title);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
