/*
 * Lollia-Center
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LoliaFrpClient.Core.Client.FileParameter;
using OpenAPIDateConverter = LoliaFrpClient.Core.Client.OpenAPIDateConverter;

namespace LoliaFrpClient.Core.Model
{
    /// <summary>
    /// UserTunnelPostRequest
    /// </summary>
    [DataContract(Name = "_user_tunnel_post_request")]
    public partial class UserTunnelPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserTunnelPostRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserTunnelPostRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserTunnelPostRequest" /> class.
        /// </summary>
        /// <param name="nodeId">nodeId (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="localIp">localIp (required).</param>
        /// <param name="localPort">localPort (required).</param>
        /// <param name="remotePort">remotePort (required).</param>
        /// <param name="customDomain">customDomain (required).</param>
        /// <param name="remark">remark (required).</param>
        public UserTunnelPostRequest(int nodeId = default, string type = default, string localIp = default, int localPort = default, int remotePort = default, string customDomain = default, string remark = default)
        {
            this.NodeId = nodeId;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for UserTunnelPostRequest and cannot be null");
            }
            this.Type = type;
            // to ensure "localIp" is required (not null)
            if (localIp == null)
            {
                throw new ArgumentNullException("localIp is a required property for UserTunnelPostRequest and cannot be null");
            }
            this.LocalIp = localIp;
            this.LocalPort = localPort;
            this.RemotePort = remotePort;
            // to ensure "customDomain" is required (not null)
            if (customDomain == null)
            {
                throw new ArgumentNullException("customDomain is a required property for UserTunnelPostRequest and cannot be null");
            }
            this.CustomDomain = customDomain;
            // to ensure "remark" is required (not null)
            if (remark == null)
            {
                throw new ArgumentNullException("remark is a required property for UserTunnelPostRequest and cannot be null");
            }
            this.Remark = remark;
        }

        /// <summary>
        /// Gets or Sets NodeId
        /// </summary>
        [DataMember(Name = "node_id", IsRequired = true, EmitDefaultValue = true)]
        public int NodeId { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets LocalIp
        /// </summary>
        [DataMember(Name = "local_ip", IsRequired = true, EmitDefaultValue = true)]
        public string LocalIp { get; set; }

        /// <summary>
        /// Gets or Sets LocalPort
        /// </summary>
        [DataMember(Name = "local_port", IsRequired = true, EmitDefaultValue = true)]
        public int LocalPort { get; set; }

        /// <summary>
        /// Gets or Sets RemotePort
        /// </summary>
        [DataMember(Name = "remote_port", IsRequired = true, EmitDefaultValue = true)]
        public int RemotePort { get; set; }

        /// <summary>
        /// Gets or Sets CustomDomain
        /// </summary>
        [DataMember(Name = "custom_domain", IsRequired = true, EmitDefaultValue = true)]
        public string CustomDomain { get; set; }

        /// <summary>
        /// Gets or Sets Remark
        /// </summary>
        [DataMember(Name = "remark", IsRequired = true, EmitDefaultValue = true)]
        public string Remark { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserTunnelPostRequest {\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  LocalIp: ").Append(LocalIp).Append("\n");
            sb.Append("  LocalPort: ").Append(LocalPort).Append("\n");
            sb.Append("  RemotePort: ").Append(RemotePort).Append("\n");
            sb.Append("  CustomDomain: ").Append(CustomDomain).Append("\n");
            sb.Append("  Remark: ").Append(Remark).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
