/*
 * Lollia-Center
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LoliaFrpClient.Core.Client.FileParameter;
using OpenAPIDateConverter = LoliaFrpClient.Core.Client.OpenAPIDateConverter;

namespace LoliaFrpClient.Core.Model
{
    /// <summary>
    /// UserInfoGet200ResponseData
    /// </summary>
    [DataContract(Name = "_user_info_get_200_response_data")]
    public partial class UserInfoGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserInfoGet200ResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserInfoGet200ResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserInfoGet200ResponseData" /> class.
        /// </summary>
        /// <param name="avatar">avatar (required).</param>
        /// <param name="bandwidthLimit">bandwidthLimit (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="email">email (required).</param>
        /// <param name="hasKyc">hasKyc (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="isBaned">isBaned (required).</param>
        /// <param name="kycStatus">kycStatus (required).</param>
        /// <param name="maxTunnelCount">maxTunnelCount (required).</param>
        /// <param name="role">role (required).</param>
        /// <param name="todayChecked">todayChecked (required).</param>
        /// <param name="trafficLimit">trafficLimit (required).</param>
        /// <param name="trafficUsed">trafficUsed (required).</param>
        /// <param name="username">username (required).</param>
        public UserInfoGet200ResponseData(string avatar = default, int bandwidthLimit = default, string createdAt = default, string email = default, bool hasKyc = default, int id = default, bool isBaned = default, string kycStatus = default, int maxTunnelCount = default, string role = default, bool todayChecked = default, int trafficLimit = default, int trafficUsed = default, string username = default)
        {
            // to ensure "avatar" is required (not null)
            if (avatar == null)
            {
                throw new ArgumentNullException("avatar is a required property for UserInfoGet200ResponseData and cannot be null");
            }
            this.Avatar = avatar;
            this.BandwidthLimit = bandwidthLimit;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for UserInfoGet200ResponseData and cannot be null");
            }
            this.CreatedAt = createdAt;
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for UserInfoGet200ResponseData and cannot be null");
            }
            this.Email = email;
            this.HasKyc = hasKyc;
            this.Id = id;
            this.IsBaned = isBaned;
            // to ensure "kycStatus" is required (not null)
            if (kycStatus == null)
            {
                throw new ArgumentNullException("kycStatus is a required property for UserInfoGet200ResponseData and cannot be null");
            }
            this.KycStatus = kycStatus;
            this.MaxTunnelCount = maxTunnelCount;
            // to ensure "role" is required (not null)
            if (role == null)
            {
                throw new ArgumentNullException("role is a required property for UserInfoGet200ResponseData and cannot be null");
            }
            this.Role = role;
            this.TodayChecked = todayChecked;
            this.TrafficLimit = trafficLimit;
            this.TrafficUsed = trafficUsed;
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for UserInfoGet200ResponseData and cannot be null");
            }
            this.Username = username;
        }

        /// <summary>
        /// Gets or Sets Avatar
        /// </summary>
        [DataMember(Name = "avatar", IsRequired = true, EmitDefaultValue = true)]
        public string Avatar { get; set; }

        /// <summary>
        /// Gets or Sets BandwidthLimit
        /// </summary>
        [DataMember(Name = "bandwidth_limit", IsRequired = true, EmitDefaultValue = true)]
        public int BandwidthLimit { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets HasKyc
        /// </summary>
        [DataMember(Name = "has_kyc", IsRequired = true, EmitDefaultValue = true)]
        public bool HasKyc { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets IsBaned
        /// </summary>
        [DataMember(Name = "is_baned", IsRequired = true, EmitDefaultValue = true)]
        public bool IsBaned { get; set; }

        /// <summary>
        /// Gets or Sets KycStatus
        /// </summary>
        [DataMember(Name = "kyc_status", IsRequired = true, EmitDefaultValue = true)]
        public string KycStatus { get; set; }

        /// <summary>
        /// Gets or Sets MaxTunnelCount
        /// </summary>
        [DataMember(Name = "max_tunnel_count", IsRequired = true, EmitDefaultValue = true)]
        public int MaxTunnelCount { get; set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", IsRequired = true, EmitDefaultValue = true)]
        public string Role { get; set; }

        /// <summary>
        /// Gets or Sets TodayChecked
        /// </summary>
        [DataMember(Name = "today_checked", IsRequired = true, EmitDefaultValue = true)]
        public bool TodayChecked { get; set; }

        /// <summary>
        /// Gets or Sets TrafficLimit
        /// </summary>
        [DataMember(Name = "traffic_limit", IsRequired = true, EmitDefaultValue = true)]
        public int TrafficLimit { get; set; }

        /// <summary>
        /// Gets or Sets TrafficUsed
        /// </summary>
        [DataMember(Name = "traffic_used", IsRequired = true, EmitDefaultValue = true)]
        public int TrafficUsed { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserInfoGet200ResponseData {\n");
            sb.Append("  Avatar: ").Append(Avatar).Append("\n");
            sb.Append("  BandwidthLimit: ").Append(BandwidthLimit).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  HasKyc: ").Append(HasKyc).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IsBaned: ").Append(IsBaned).Append("\n");
            sb.Append("  KycStatus: ").Append(KycStatus).Append("\n");
            sb.Append("  MaxTunnelCount: ").Append(MaxTunnelCount).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  TodayChecked: ").Append(TodayChecked).Append("\n");
            sb.Append("  TrafficLimit: ").Append(TrafficLimit).Append("\n");
            sb.Append("  TrafficUsed: ").Append(TrafficUsed).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
