/*
 * Lollia-Center
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LoliaFrpClient.Core.Client.FileParameter;
using OpenAPIDateConverter = LoliaFrpClient.Core.Client.OpenAPIDateConverter;

namespace LoliaFrpClient.Core.Model
{
    /// <summary>
    /// UserFrpcConfigGet200ResponseData
    /// </summary>
    [DataContract(Name = "_user_frpc_config_get_200_response_data")]
    public partial class UserFrpcConfigGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserFrpcConfigGet200ResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserFrpcConfigGet200ResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserFrpcConfigGet200ResponseData" /> class.
        /// </summary>
        /// <param name="config">config (required).</param>
        public UserFrpcConfigGet200ResponseData(string config = default)
        {
            // to ensure "config" is required (not null)
            if (config == null)
            {
                throw new ArgumentNullException("config is a required property for UserFrpcConfigGet200ResponseData and cannot be null");
            }
            this.Config = config;
        }

        /// <summary>
        /// Gets or Sets Config
        /// </summary>
        [DataMember(Name = "config", IsRequired = true, EmitDefaultValue = true)]
        public string Config { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserFrpcConfigGet200ResponseData {\n");
            sb.Append("  Config: ").Append(Config).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
