/*
 * Lollia-Center
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LoliaFrpClient.Core.Client.FileParameter;
using OpenAPIDateConverter = LoliaFrpClient.Core.Client.OpenAPIDateConverter;

namespace LoliaFrpClient.Core.Model
{
    /// <summary>
    /// UserOauthAppIdGet200ResponseData
    /// </summary>
    [DataContract(Name = "_user_oauth_app__id__get_200_response_data")]
    public partial class UserOauthAppIdGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserOauthAppIdGet200ResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserOauthAppIdGet200ResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserOauthAppIdGet200ResponseData" /> class.
        /// </summary>
        /// <param name="clientId">clientId (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="description">description (required).</param>
        /// <param name="homepage">homepage (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="isActive">isActive (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="redirectUris">redirectUris (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public UserOauthAppIdGet200ResponseData(string clientId = default, string createdAt = default, string description = default, string homepage = default, int id = default, bool isActive = default, string name = default, List<string> redirectUris = default, string updatedAt = default)
        {
            // to ensure "clientId" is required (not null)
            if (clientId == null)
            {
                throw new ArgumentNullException("clientId is a required property for UserOauthAppIdGet200ResponseData and cannot be null");
            }
            this.ClientId = clientId;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for UserOauthAppIdGet200ResponseData and cannot be null");
            }
            this.CreatedAt = createdAt;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for UserOauthAppIdGet200ResponseData and cannot be null");
            }
            this.Description = description;
            // to ensure "homepage" is required (not null)
            if (homepage == null)
            {
                throw new ArgumentNullException("homepage is a required property for UserOauthAppIdGet200ResponseData and cannot be null");
            }
            this.Homepage = homepage;
            this.Id = id;
            this.IsActive = isActive;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for UserOauthAppIdGet200ResponseData and cannot be null");
            }
            this.Name = name;
            // to ensure "redirectUris" is required (not null)
            if (redirectUris == null)
            {
                throw new ArgumentNullException("redirectUris is a required property for UserOauthAppIdGet200ResponseData and cannot be null");
            }
            this.RedirectUris = redirectUris;
            // to ensure "updatedAt" is required (not null)
            if (updatedAt == null)
            {
                throw new ArgumentNullException("updatedAt is a required property for UserOauthAppIdGet200ResponseData and cannot be null");
            }
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets ClientId
        /// </summary>
        [DataMember(Name = "client_id", IsRequired = true, EmitDefaultValue = true)]
        public string ClientId { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Homepage
        /// </summary>
        [DataMember(Name = "homepage", IsRequired = true, EmitDefaultValue = true)]
        public string Homepage { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [DataMember(Name = "is_active", IsRequired = true, EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets RedirectUris
        /// </summary>
        [DataMember(Name = "redirect_uris", IsRequired = true, EmitDefaultValue = true)]
        public List<string> RedirectUris { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updated_at", IsRequired = true, EmitDefaultValue = true)]
        public string UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserOauthAppIdGet200ResponseData {\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Homepage: ").Append(Homepage).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RedirectUris: ").Append(RedirectUris).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
