/*
 * Lollia-Center
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LoliaFrpClient.Core.Client.FileParameter;
using OpenAPIDateConverter = LoliaFrpClient.Core.Client.OpenAPIDateConverter;

namespace LoliaFrpClient.Core.Model
{
    /// <summary>
    /// UserTunnelTunnelNameGet200ResponseData
    /// </summary>
    [DataContract(Name = "_user_tunnel__tunnel_name__get_200_response_data")]
    public partial class UserTunnelTunnelNameGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserTunnelTunnelNameGet200ResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserTunnelTunnelNameGet200ResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserTunnelTunnelNameGet200ResponseData" /> class.
        /// </summary>
        /// <param name="bandwidthLimit">bandwidthLimit (required).</param>
        /// <param name="clientVersion">clientVersion (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="customDomain">customDomain (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="localIp">localIp (required).</param>
        /// <param name="localPort">localPort (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="nodeAddress">nodeAddress (required).</param>
        /// <param name="nodeId">nodeId (required).</param>
        /// <param name="nodeName">nodeName (required).</param>
        /// <param name="remark">remark (required).</param>
        /// <param name="remotePort">remotePort (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="tunnelToken">tunnelToken (required).</param>
        /// <param name="type">type (required).</param>
        public UserTunnelTunnelNameGet200ResponseData(int bandwidthLimit = default, string clientVersion = default, string createdAt = default, string customDomain = default, int id = default, string localIp = default, int localPort = default, string name = default, string nodeAddress = default, int nodeId = default, string nodeName = default, string remark = default, int remotePort = default, string status = default, string tunnelToken = default, string type = default)
        {
            this.BandwidthLimit = bandwidthLimit;
            // to ensure "clientVersion" is required (not null)
            if (clientVersion == null)
            {
                throw new ArgumentNullException("clientVersion is a required property for UserTunnelTunnelNameGet200ResponseData and cannot be null");
            }
            this.ClientVersion = clientVersion;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for UserTunnelTunnelNameGet200ResponseData and cannot be null");
            }
            this.CreatedAt = createdAt;
            // to ensure "customDomain" is required (not null)
            if (customDomain == null)
            {
                throw new ArgumentNullException("customDomain is a required property for UserTunnelTunnelNameGet200ResponseData and cannot be null");
            }
            this.CustomDomain = customDomain;
            this.Id = id;
            // to ensure "localIp" is required (not null)
            if (localIp == null)
            {
                throw new ArgumentNullException("localIp is a required property for UserTunnelTunnelNameGet200ResponseData and cannot be null");
            }
            this.LocalIp = localIp;
            this.LocalPort = localPort;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for UserTunnelTunnelNameGet200ResponseData and cannot be null");
            }
            this.Name = name;
            // to ensure "nodeAddress" is required (not null)
            if (nodeAddress == null)
            {
                throw new ArgumentNullException("nodeAddress is a required property for UserTunnelTunnelNameGet200ResponseData and cannot be null");
            }
            this.NodeAddress = nodeAddress;
            this.NodeId = nodeId;
            // to ensure "nodeName" is required (not null)
            if (nodeName == null)
            {
                throw new ArgumentNullException("nodeName is a required property for UserTunnelTunnelNameGet200ResponseData and cannot be null");
            }
            this.NodeName = nodeName;
            // to ensure "remark" is required (not null)
            if (remark == null)
            {
                throw new ArgumentNullException("remark is a required property for UserTunnelTunnelNameGet200ResponseData and cannot be null");
            }
            this.Remark = remark;
            this.RemotePort = remotePort;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for UserTunnelTunnelNameGet200ResponseData and cannot be null");
            }
            this.Status = status;
            // to ensure "tunnelToken" is required (not null)
            if (tunnelToken == null)
            {
                throw new ArgumentNullException("tunnelToken is a required property for UserTunnelTunnelNameGet200ResponseData and cannot be null");
            }
            this.TunnelToken = tunnelToken;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for UserTunnelTunnelNameGet200ResponseData and cannot be null");
            }
            this.Type = type;
        }

        /// <summary>
        /// Gets or Sets BandwidthLimit
        /// </summary>
        [DataMember(Name = "bandwidth_limit", IsRequired = true, EmitDefaultValue = true)]
        public int BandwidthLimit { get; set; }

        /// <summary>
        /// Gets or Sets ClientVersion
        /// </summary>
        [DataMember(Name = "client_version", IsRequired = true, EmitDefaultValue = true)]
        public string ClientVersion { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets CustomDomain
        /// </summary>
        [DataMember(Name = "custom_domain", IsRequired = true, EmitDefaultValue = true)]
        public string CustomDomain { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets LocalIp
        /// </summary>
        [DataMember(Name = "local_ip", IsRequired = true, EmitDefaultValue = true)]
        public string LocalIp { get; set; }

        /// <summary>
        /// Gets or Sets LocalPort
        /// </summary>
        [DataMember(Name = "local_port", IsRequired = true, EmitDefaultValue = true)]
        public int LocalPort { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets NodeAddress
        /// </summary>
        [DataMember(Name = "node_address", IsRequired = true, EmitDefaultValue = true)]
        public string NodeAddress { get; set; }

        /// <summary>
        /// Gets or Sets NodeId
        /// </summary>
        [DataMember(Name = "node_id", IsRequired = true, EmitDefaultValue = true)]
        public int NodeId { get; set; }

        /// <summary>
        /// Gets or Sets NodeName
        /// </summary>
        [DataMember(Name = "node_name", IsRequired = true, EmitDefaultValue = true)]
        public string NodeName { get; set; }

        /// <summary>
        /// Gets or Sets Remark
        /// </summary>
        [DataMember(Name = "remark", IsRequired = true, EmitDefaultValue = true)]
        public string Remark { get; set; }

        /// <summary>
        /// Gets or Sets RemotePort
        /// </summary>
        [DataMember(Name = "remote_port", IsRequired = true, EmitDefaultValue = true)]
        public int RemotePort { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets TunnelToken
        /// </summary>
        [DataMember(Name = "tunnel_token", IsRequired = true, EmitDefaultValue = true)]
        public string TunnelToken { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserTunnelTunnelNameGet200ResponseData {\n");
            sb.Append("  BandwidthLimit: ").Append(BandwidthLimit).Append("\n");
            sb.Append("  ClientVersion: ").Append(ClientVersion).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  CustomDomain: ").Append(CustomDomain).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LocalIp: ").Append(LocalIp).Append("\n");
            sb.Append("  LocalPort: ").Append(LocalPort).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NodeAddress: ").Append(NodeAddress).Append("\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  NodeName: ").Append(NodeName).Append("\n");
            sb.Append("  Remark: ").Append(Remark).Append("\n");
            sb.Append("  RemotePort: ").Append(RemotePort).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TunnelToken: ").Append(TunnelToken).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
