// <auto-generated/>
#pragma warning disable CS0618
using LoliaFrpClient.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Api.Releases.Detail
{
    /// <summary>
    /// Builds and executes requests for operations under \releases\detail
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DetailRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Releases.Detail.DetailRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DetailRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/releases/detail?release_id={release_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Releases.Detail.DetailRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DetailRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/releases/detail?release_id={release_id}", rawUrl)
        {
        }
        /// <summary>
        /// 返回软件信息、配置的最新可见版本和已启用的下载源。未设置最新版本或该版本不可见时 latest_version 为 null。仅提供已启用且上游可用的版本；GitHub 模式未开启 include_prerelease 时隐藏预发布版本。鉴权：Authorization: Bearer &lt;token&gt;，支持用户 JWT 和 OAuth2 Access Token。OAuth2 需要 release:read，release:* 或 all 也可授权。
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Models.ReleaseDetailResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.Models.ReleaseDetailResponse?> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.Releases.Detail.DetailRequestBuilder.DetailRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.Models.ReleaseDetailResponse> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.Releases.Detail.DetailRequestBuilder.DetailRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.Models.ReleaseDetailResponse>(requestInfo, global::LoliaFrpClient.Api.Models.ReleaseDetailResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 返回软件信息、配置的最新可见版本和已启用的下载源。未设置最新版本或该版本不可见时 latest_version 为 null。仅提供已启用且上游可用的版本；GitHub 模式未开启 include_prerelease 时隐藏预发布版本。鉴权：Authorization: Bearer &lt;token&gt;，支持用户 JWT 和 OAuth2 Access Token。OAuth2 需要 release:read，release:* 或 all 也可授权。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Api.Releases.Detail.DetailRequestBuilder.DetailRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Api.Releases.Detail.DetailRequestBuilder.DetailRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Releases.Detail.DetailRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Api.Releases.Detail.DetailRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Api.Releases.Detail.DetailRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 返回软件信息、配置的最新可见版本和已启用的下载源。未设置最新版本或该版本不可见时 latest_version 为 null。仅提供已启用且上游可用的版本；GitHub 模式未开启 include_prerelease 时隐藏预发布版本。鉴权：Authorization: Bearer &lt;token&gt;，支持用户 JWT 和 OAuth2 Access Token。OAuth2 需要 release:read，release:* 或 all 也可授权。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DetailRequestBuilderGetQueryParameters 
        {
            /// <summary>软件 ID，必须且只能在 query 中传入一次。</summary>
            [QueryParameter("release_id")]
            public long? ReleaseId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DetailRequestBuilderGetRequestConfiguration : RequestConfiguration<global::LoliaFrpClient.Api.Releases.Detail.DetailRequestBuilder.DetailRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
