// <auto-generated/>
#pragma warning disable CS0618
using LoliaFrpClient.Core.Tunnel.Frpc.Config.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LoliaFrpClient.Core.Tunnel.Frpc.Config
{
    /// <summary>
    /// Builds and executes requests for operations under \tunnel\frpc\config
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConfigRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LoliaFrpClient.Core.tunnel.frpc.config.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Tunnel.Frpc.Config.Item.WithTokenItemRequestBuilder"/></returns>
        public global::LoliaFrpClient.Core.Tunnel.Frpc.Config.Item.WithTokenItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("token", position);
                return new global::LoliaFrpClient.Core.Tunnel.Frpc.Config.Item.WithTokenItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.Tunnel.Frpc.Config.ConfigRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tunnel/frpc/config", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.Tunnel.Frpc.Config.ConfigRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tunnel/frpc/config", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
