// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Api.User.Kyc.Status
{
    /// <summary>
    /// Builds and executes requests for operations under \user\kyc\status
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.User.Kyc.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/kyc/status", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.User.Kyc.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/kyc/status", rawUrl)
        {
        }
        /// <summary>
        /// 获取当前用户的实名认证记录状态（仅读数据库）。无认证记录返回 404。成功 msg：查询成功。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | 此接口不支持OAuth2访问 || 401 | 未授权 || 404 | 未找到认证记录 || 500 | 查询认证记录失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Kyc.Status.StatusGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.User.Kyc.Status.Status401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Kyc.Status.Status403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Kyc.Status.Status404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Kyc.Status.Status500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Kyc.Status.Status503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.User.Kyc.Status.StatusGetResponse?> GetAsStatusGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.User.Kyc.Status.StatusGetResponse> GetAsStatusGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Api.User.Kyc.Status.Status401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.User.Kyc.Status.Status403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Api.User.Kyc.Status.Status404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.User.Kyc.Status.Status500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Api.User.Kyc.Status.Status503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.User.Kyc.Status.StatusGetResponse>(requestInfo, global::LoliaFrpClient.Api.User.Kyc.Status.StatusGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取当前用户的实名认证记录状态（仅读数据库）。无认证记录返回 404。成功 msg：查询成功。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | 此接口不支持OAuth2访问 || 401 | 未授权 || 404 | 未找到认证记录 || 500 | 查询认证记录失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Kyc.Status.StatusResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.User.Kyc.Status.Status401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Kyc.Status.Status403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Kyc.Status.Status404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Kyc.Status.Status500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Kyc.Status.Status503Error">When receiving a 503 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsStatusGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.User.Kyc.Status.StatusResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.User.Kyc.Status.StatusResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Api.User.Kyc.Status.Status401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.User.Kyc.Status.Status403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Api.User.Kyc.Status.Status404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.User.Kyc.Status.Status500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Api.User.Kyc.Status.Status503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.User.Kyc.Status.StatusResponse>(requestInfo, global::LoliaFrpClient.Api.User.Kyc.Status.StatusResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取当前用户的实名认证记录状态（仅读数据库）。无认证记录返回 404。成功 msg：查询成功。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | 此接口不支持OAuth2访问 || 401 | 未授权 || 404 | 未找到认证记录 || 500 | 查询认证记录失败 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Kyc.Status.StatusRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Api.User.Kyc.Status.StatusRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Api.User.Kyc.Status.StatusRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StatusRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
