// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace LoliaFrpClient.Api.User.Billing.Bills
{
    /// <summary>商品类型，仅支持 kyc_fee</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BillsPostRequestBody_product_type
    {
        [EnumMember(Value = "kyc_fee")]
        #pragma warning disable CS1591
        Kyc_fee,
        #pragma warning restore CS1591
    }
}
