// <auto-generated/>
#pragma warning disable CS0618
using LoliaFrpClient.Core.Admin.User.Item.Ban;
using LoliaFrpClient.Core.Admin.User.Item.Traffic;
using LoliaFrpClient.Core.Admin.User.Item.Tunnels;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Core.Admin.User.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\user\{user_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUser_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ban property</summary>
        public global::LoliaFrpClient.Core.Admin.User.Item.Ban.BanRequestBuilder Ban
        {
            get => new global::LoliaFrpClient.Core.Admin.User.Item.Ban.BanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The traffic property</summary>
        public global::LoliaFrpClient.Core.Admin.User.Item.Traffic.TrafficRequestBuilder Traffic
        {
            get => new global::LoliaFrpClient.Core.Admin.User.Item.Traffic.TrafficRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tunnels property</summary>
        public global::LoliaFrpClient.Core.Admin.User.Item.Tunnels.TunnelsRequestBuilder Tunnels
        {
            get => new global::LoliaFrpClient.Core.Admin.User.Item.Tunnels.TunnelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUser_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/user/{user_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUser_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/user/{user_id}", rawUrl)
        {
        }
        /// <summary>
        /// 获取用户基础信息、流量信息与活跃会话数；若用户流量记录不存在会自动创建。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 用户ID格式错误 || 404 | 用户不存在 || 500 | 获取用户信息失败 || 500 | 获取用户流量失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_GetResponse?> GetAsWithUser_GetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_GetResponse> GetAsWithUser_GetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_GetResponse>(requestInfo, global::LoliaFrpClient.Core.Admin.User.Item.WithUser_GetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取用户基础信息、流量信息与活跃会话数；若用户流量记录不存在会自动创建。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 用户ID格式错误 || 404 | 用户不存在 || 500 | 获取用户信息失败 || 500 | 获取用户流量失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsWithUser_GetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_Response>(requestInfo, global::LoliaFrpClient.Core.Admin.User.Item.WithUser_Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 部分更新用户信息：所有字段均可选，不传或为 null 表示不修改。traffic_limit 为剩余流量（字节）并直接覆盖。修改后清理用户信息缓存并返回更新后的数据。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 用户ID格式错误 || 400 | 请求参数错误: &lt;校验错误详情&gt; || 400 | 用户名不能为空 || 404 | 用户不存在 || 409 | 用户名已存在 || 409 | 邮箱已存在 || 500 | 更新用户信息失败 || 500 | 更新剩余流量失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_PutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_PutResponse?> PutAsWithUser_PutResponseAsync(global::LoliaFrpClient.Core.Admin.User.Item.WithUser_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_PutResponse> PutAsWithUser_PutResponseAsync(global::LoliaFrpClient.Core.Admin.User.Item.WithUser_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_404Error.CreateFromDiscriminatorValue },
                { "409", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_409Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_PutResponse>(requestInfo, global::LoliaFrpClient.Core.Admin.User.Item.WithUser_PutResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 部分更新用户信息：所有字段均可选，不传或为 null 表示不修改。traffic_limit 为剩余流量（字节）并直接覆盖。修改后清理用户信息缓存并返回更新后的数据。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 用户ID格式错误 || 400 | 请求参数错误: &lt;校验错误详情&gt; || 400 | 用户名不能为空 || 404 | 用户不存在 || 409 | 用户名已存在 || 409 | 邮箱已存在 || 500 | 更新用户信息失败 || 500 | 更新剩余流量失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PutAsWithUser_PutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_Response?> PutAsync(global::LoliaFrpClient.Core.Admin.User.Item.WithUser_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_Response> PutAsync(global::LoliaFrpClient.Core.Admin.User.Item.WithUser_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_404Error.CreateFromDiscriminatorValue },
                { "409", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_409Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Admin.User.Item.WithUser_500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Admin.User.Item.WithUser_Response>(requestInfo, global::LoliaFrpClient.Core.Admin.User.Item.WithUser_Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取用户基础信息、流量信息与活跃会话数；若用户流量记录不存在会自动创建。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 用户ID格式错误 || 404 | 用户不存在 || 500 | 获取用户信息失败 || 500 | 获取用户流量失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// 部分更新用户信息：所有字段均可选，不传或为 null 表示不修改。traffic_limit 为剩余流量（字节）并直接覆盖。修改后清理用户信息缓存并返回更新后的数据。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 用户ID格式错误 || 400 | 请求参数错误: &lt;校验错误详情&gt; || 400 | 用户名不能为空 || 404 | 用户不存在 || 409 | 用户名已存在 || 409 | 邮箱已存在 || 500 | 更新用户信息失败 || 500 | 更新剩余流量失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::LoliaFrpClient.Core.Admin.User.Item.WithUser_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::LoliaFrpClient.Core.Admin.User.Item.WithUser_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.User.Item.WithUser_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Core.Admin.User.Item.WithUser_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Core.Admin.User.Item.WithUser_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithUser_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithUser_ItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
