// <auto-generated/>
#pragma warning disable CS0618
using LoliaFrpClient.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Api.Releases.Download
{
    /// <summary>
    /// Builds and executes requests for operations under \releases\download
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DownloadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Releases.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/releases/download?release_id={release_id}&source={source}{&arch*,asset_id*,os*,version*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Releases.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/releases/download?release_id={release_id}&source={source}{&arch*,asset_id*,os*,version*}", rawUrl)
        {
        }
        /// <summary>
        /// 返回包含下载 URL 的 JSON，客户端再请求 data.url 下载文件。成功响应带 Cache-Control: no-store。必须明确指定 source（direct 或下载源 ID 字符串），且该源必须对软件启用并具有当前文件的可用副本；不可用时返回 409，不自动回退。指定 asset_id 时直接选择文件，可省略平台和 version；若同时传入 version/os/arch，必须与文件匹配。未指定 asset_id 时，version 为空或 latest 表示配置的最新版本，其他值按版本 tag 精确匹配。优先使用显式 os/arch，缺失部分从 Client Hints 和 User-Agent 推断；仍缺失则返回 422 platform_required。平台匹配包含 any 通用文件；无匹配返回 404，多文件匹配返回 422 asset_ambiguous。S3 返回临时签名 URL 及 expires_at；direct 和 GitHub 镜像返回地址且 expires_at 为 null。仅提供已启用且上游可用的版本；GitHub 模式未开启 include_prerelease 时隐藏预发布版本。鉴权：Authorization: Bearer &lt;token&gt;，支持用户 JWT 和 OAuth2 Access Token。OAuth2 需要 release:read，release:* 或 all 也可授权。
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Models.ReleaseDownloadResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 409 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError">When receiving a 422 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 502 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Models.ReleaseError">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.Models.ReleaseDownloadResponse?> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.Releases.Download.DownloadRequestBuilder.DownloadRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.Models.ReleaseDownloadResponse> GetAsync(Action<RequestConfiguration<global::LoliaFrpClient.Api.Releases.Download.DownloadRequestBuilder.DownloadRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "409", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "422", global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "502", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Api.Models.ReleaseError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.Models.ReleaseDownloadResponse>(requestInfo, global::LoliaFrpClient.Api.Models.ReleaseDownloadResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 返回包含下载 URL 的 JSON，客户端再请求 data.url 下载文件。成功响应带 Cache-Control: no-store。必须明确指定 source（direct 或下载源 ID 字符串），且该源必须对软件启用并具有当前文件的可用副本；不可用时返回 409，不自动回退。指定 asset_id 时直接选择文件，可省略平台和 version；若同时传入 version/os/arch，必须与文件匹配。未指定 asset_id 时，version 为空或 latest 表示配置的最新版本，其他值按版本 tag 精确匹配。优先使用显式 os/arch，缺失部分从 Client Hints 和 User-Agent 推断；仍缺失则返回 422 platform_required。平台匹配包含 any 通用文件；无匹配返回 404，多文件匹配返回 422 asset_ambiguous。S3 返回临时签名 URL 及 expires_at；direct 和 GitHub 镜像返回地址且 expires_at 为 null。仅提供已启用且上游可用的版本；GitHub 模式未开启 include_prerelease 时隐藏预发布版本。鉴权：Authorization: Bearer &lt;token&gt;，支持用户 JWT 和 OAuth2 Access Token。OAuth2 需要 release:read，release:* 或 all 也可授权。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Api.Releases.Download.DownloadRequestBuilder.DownloadRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LoliaFrpClient.Api.Releases.Download.DownloadRequestBuilder.DownloadRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Releases.Download.DownloadRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Api.Releases.Download.DownloadRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Api.Releases.Download.DownloadRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 返回包含下载 URL 的 JSON，客户端再请求 data.url 下载文件。成功响应带 Cache-Control: no-store。必须明确指定 source（direct 或下载源 ID 字符串），且该源必须对软件启用并具有当前文件的可用副本；不可用时返回 409，不自动回退。指定 asset_id 时直接选择文件，可省略平台和 version；若同时传入 version/os/arch，必须与文件匹配。未指定 asset_id 时，version 为空或 latest 表示配置的最新版本，其他值按版本 tag 精确匹配。优先使用显式 os/arch，缺失部分从 Client Hints 和 User-Agent 推断；仍缺失则返回 422 platform_required。平台匹配包含 any 通用文件；无匹配返回 404，多文件匹配返回 422 asset_ambiguous。S3 返回临时签名 URL 及 expires_at；direct 和 GitHub 镜像返回地址且 expires_at 为 null。仅提供已启用且上游可用的版本；GitHub 模式未开启 include_prerelease 时隐藏预发布版本。鉴权：Authorization: Bearer &lt;token&gt;，支持用户 JWT 和 OAuth2 Access Token。OAuth2 需要 release:read，release:* 或 all 也可授权。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DownloadRequestBuilderGetQueryParameters 
        {
            /// <summary>架构名，不区分大小写并去除首尾空白。支持 amd64（x86_64/x64）、arm64（aarch64）、386（i386/i686/x86）、arm（armv7/armv6/armhf）、riscv64、mips、mipsle、mips64、mips64le、ppc64、ppc64le、s390x、any（all/universal）。非空无效值返回 400；匹配时包含 any 通用文件。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("arch")]
            public string? Arch { get; set; }
#nullable restore
#else
            [QueryParameter("arch")]
            public string Arch { get; set; }
#endif
            /// <summary>明确指定目标文件 ID；文件必须属于当前软件的可见版本。</summary>
            [QueryParameter("asset_id")]
            public long? AssetId { get; set; }
            /// <summary>系统名，不区分大小写并去除首尾空白。支持 windows（win/win32/win64）、darwin（mac/macos/osx）、linux、freebsd、openbsd、android、ios、any（all）。非空无效值返回 400；匹配时包含 any 通用文件。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("os")]
            public string? Os { get; set; }
#nullable restore
#else
            [QueryParameter("os")]
            public string Os { get; set; }
#endif
            /// <summary>软件 ID，必须且只能在 query 中传入一次。</summary>
            [QueryParameter("release_id")]
            public long? ReleaseId { get; set; }
            /// <summary>必须且只能出现一次。direct 表示 GitHub 原始下载；其他值为 1–4294967295 的十进制下载源 ID 字符串。建议直接使用 available_sources 中的 source。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("source")]
            public string? Source { get; set; }
#nullable restore
#else
            [QueryParameter("source")]
            public string Source { get; set; }
#endif
            /// <summary>版本 tag 或 latest；不传 asset_id 时，省略/空字符串等同 latest。指定 asset_id 时省略此参数表示使用文件所属版本。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("version")]
            public string? Version { get; set; }
#nullable restore
#else
            [QueryParameter("version")]
            public string Version { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DownloadRequestBuilderGetRequestConfiguration : RequestConfiguration<global::LoliaFrpClient.Api.Releases.Download.DownloadRequestBuilder.DownloadRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
