// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Api.Qqbot.Qq.Bind
{
    /// <summary>
    /// Builds and executes requests for operations under \qqbot\qq\bind
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BindRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BindRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qqbot/qq/bind", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BindRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qqbot/qq/bind", rawUrl)
        {
        }
        /// <summary>
        /// QQ 机器人使用挑战值为网站用户绑定 QQ。流程：用户在网站调用 POST /user/qq/challenge 获取一次性挑战值（10 分钟有效）→ 用户把挑战值发给 QQ 机器人 → 机器人携带挑战值与发送者 QQ 号调用本接口。挑战值一次性消费（无论后续是否成功）。同一 QQ 号不能绑定多个用户；已绑定用户会被覆盖为新 QQ 号。**鉴权**：QQ 机器人鉴权（见请求头）**错误响应**：| code | msg || --- | --- || 500 | qqbot token not configured || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid qqbot token || 400 | 请求参数错误: &lt;校验错误详情&gt; || 400 | 挑战值不能为空 || 400 | QQ号格式错误 || 404 | 挑战值不存在或已过期 || 404 | 用户不存在 || 409 | 该QQ号已绑定其他用户 || 500 | 校验挑战值失败 || 500 | 获取用户信息失败 || 500 | 校验QQ绑定状态失败 || 500 | 绑定QQ失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindPostResponse?> PostAsBindPostResponseAsync(global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindPostResponse> PostAsBindPostResponseAsync(global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind401Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind404Error.CreateFromDiscriminatorValue },
                { "409", global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind409Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindPostResponse>(requestInfo, global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// QQ 机器人使用挑战值为网站用户绑定 QQ。流程：用户在网站调用 POST /user/qq/challenge 获取一次性挑战值（10 分钟有效）→ 用户把挑战值发给 QQ 机器人 → 机器人携带挑战值与发送者 QQ 号调用本接口。挑战值一次性消费（无论后续是否成功）。同一 QQ 号不能绑定多个用户；已绑定用户会被覆盖为新 QQ 号。**鉴权**：QQ 机器人鉴权（见请求头）**错误响应**：| code | msg || --- | --- || 500 | qqbot token not configured || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid qqbot token || 400 | 请求参数错误: &lt;校验错误详情&gt; || 400 | 挑战值不能为空 || 400 | QQ号格式错误 || 404 | 挑战值不存在或已过期 || 404 | 用户不存在 || 409 | 该QQ号已绑定其他用户 || 500 | 校验挑战值失败 || 500 | 获取用户信息失败 || 500 | 校验QQ绑定状态失败 || 500 | 绑定QQ失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsBindPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindResponse?> PostAsync(global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindResponse> PostAsync(global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind401Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind404Error.CreateFromDiscriminatorValue },
                { "409", global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind409Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.Qqbot.Qq.Bind.Bind500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindResponse>(requestInfo, global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// QQ 机器人使用挑战值为网站用户绑定 QQ。流程：用户在网站调用 POST /user/qq/challenge 获取一次性挑战值（10 分钟有效）→ 用户把挑战值发给 QQ 机器人 → 机器人携带挑战值与发送者 QQ 号调用本接口。挑战值一次性消费（无论后续是否成功）。同一 QQ 号不能绑定多个用户；已绑定用户会被覆盖为新 QQ 号。**鉴权**：QQ 机器人鉴权（见请求头）**错误响应**：| code | msg || --- | --- || 500 | qqbot token not configured || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid qqbot token || 400 | 请求参数错误: &lt;校验错误详情&gt; || 400 | 挑战值不能为空 || 400 | QQ号格式错误 || 404 | 挑战值不存在或已过期 || 404 | 用户不存在 || 409 | 该QQ号已绑定其他用户 || 500 | 校验挑战值失败 || 500 | 获取用户信息失败 || 500 | 校验QQ绑定状态失败 || 500 | 绑定QQ失败 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Api.Qqbot.Qq.Bind.BindRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BindRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
