// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Core.Oauth2.Token
{
    /// <summary>
    /// Builds and executes requests for operations under \oauth2\token
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TokenRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.Oauth2.Token.TokenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokenRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth2/token", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.Oauth2.Token.TokenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokenRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth2/token", rawUrl)
        {
        }
        /// <summary>
        /// 授权码流程第 3 步（服务端/客户端调用，无需用户登录态）。支持 grant_type：authorization_code（用授权码换令牌）与 refresh_token（刷新访问令牌）。请求体支持 application/x-www-form-urlencoded（推荐，RFC 标准）或 application/json，按 Content-Type 自动识别。客户端认证：仅支持在请求体中传 client_id + client_secret（client_secret_post），不支持 HTTP Basic（Authorization 头会被忽略）；public 客户端无需 client_secret。authorization_code：code 与 redirect_uri 必填，redirect_uri 须与 approve 时完全一致；授权码一次性、10 分钟有效；若授权时使用了 PKCE 则必须传 code_verifier（43~128 位 [A-Za-z0-9-._~]），public 客户端必须使用 PKCE。refresh_token：refresh_token 必填，会签发新 access_token 并使旧令牌失效，refresh_token 本身保持不变且过期时间不延长。被封禁用户无法换取/刷新令牌。所有响应均为 RFC 6749 风格：成功为标准令牌 JSON，失败为 {error, error_description}，均不使用 code/msg/data 包装。**鉴权**：OAuth2 客户端鉴权（client_id / client_secret）**错误响应**：| code | msg || --- | --- || 400 | invalid_request: 请求参数错误: &lt;校验错误详情&gt; || 401 | invalid_client: 无效的客户端ID || 401 | invalid_client: 应用已停用 || 401 | invalid_client: 客户端认证失败 || 400 | invalid_request: 缺少code或redirect_uri参数 || 400 | invalid_grant: 无效的授权码 || 400 | invalid_grant: 授权码已过期 || 400 | invalid_grant: 授权码已被使用 || 400 | invalid_grant: 授权码验证失败 || 400 | invalid_grant: public 客户端必须使用 PKCE || 400 | invalid_request: 缺少 code_verifier 参数 || 400 | invalid_grant: code_verifier 校验失败 || 400 | invalid_grant: PKCE 校验失败 || 400 | invalid_grant: 用户不可用 || 400 | invalid_request: 缺少refresh_token参数 || 400 | invalid_grant: 无效的刷新令牌 || 400 | invalid_grant: 刷新令牌已过期 || 400 | invalid_grant: 客户端ID不匹配 || 400 | unsupported_grant_type: 不支持的grant_type: &lt;grant_type&gt; || 500 | server_error: 内部错误 || 500 | server_error: 授权码处理失败 || 500 | server_error: 查询用户状态失败 || 500 | server_error: 生成令牌失败 || 500 | server_error: 创建令牌失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Oauth2.Token.TokenPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Oauth2.Token.Token400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Oauth2.Token.Token401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Oauth2.Token.Token500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Oauth2.Token.TokenPostResponse?> PostAsTokenPostResponseAsync(global::LoliaFrpClient.Core.Oauth2.Token.TokenPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Oauth2.Token.TokenPostResponse> PostAsTokenPostResponseAsync(global::LoliaFrpClient.Core.Oauth2.Token.TokenPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Oauth2.Token.Token400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Oauth2.Token.Token401Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Oauth2.Token.Token500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Oauth2.Token.TokenPostResponse>(requestInfo, global::LoliaFrpClient.Core.Oauth2.Token.TokenPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 授权码流程第 3 步（服务端/客户端调用，无需用户登录态）。支持 grant_type：authorization_code（用授权码换令牌）与 refresh_token（刷新访问令牌）。请求体支持 application/x-www-form-urlencoded（推荐，RFC 标准）或 application/json，按 Content-Type 自动识别。客户端认证：仅支持在请求体中传 client_id + client_secret（client_secret_post），不支持 HTTP Basic（Authorization 头会被忽略）；public 客户端无需 client_secret。authorization_code：code 与 redirect_uri 必填，redirect_uri 须与 approve 时完全一致；授权码一次性、10 分钟有效；若授权时使用了 PKCE 则必须传 code_verifier（43~128 位 [A-Za-z0-9-._~]），public 客户端必须使用 PKCE。refresh_token：refresh_token 必填，会签发新 access_token 并使旧令牌失效，refresh_token 本身保持不变且过期时间不延长。被封禁用户无法换取/刷新令牌。所有响应均为 RFC 6749 风格：成功为标准令牌 JSON，失败为 {error, error_description}，均不使用 code/msg/data 包装。**鉴权**：OAuth2 客户端鉴权（client_id / client_secret）**错误响应**：| code | msg || --- | --- || 400 | invalid_request: 请求参数错误: &lt;校验错误详情&gt; || 401 | invalid_client: 无效的客户端ID || 401 | invalid_client: 应用已停用 || 401 | invalid_client: 客户端认证失败 || 400 | invalid_request: 缺少code或redirect_uri参数 || 400 | invalid_grant: 无效的授权码 || 400 | invalid_grant: 授权码已过期 || 400 | invalid_grant: 授权码已被使用 || 400 | invalid_grant: 授权码验证失败 || 400 | invalid_grant: public 客户端必须使用 PKCE || 400 | invalid_request: 缺少 code_verifier 参数 || 400 | invalid_grant: code_verifier 校验失败 || 400 | invalid_grant: PKCE 校验失败 || 400 | invalid_grant: 用户不可用 || 400 | invalid_request: 缺少refresh_token参数 || 400 | invalid_grant: 无效的刷新令牌 || 400 | invalid_grant: 刷新令牌已过期 || 400 | invalid_grant: 客户端ID不匹配 || 400 | unsupported_grant_type: 不支持的grant_type: &lt;grant_type&gt; || 500 | server_error: 内部错误 || 500 | server_error: 授权码处理失败 || 500 | server_error: 查询用户状态失败 || 500 | server_error: 生成令牌失败 || 500 | server_error: 创建令牌失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Oauth2.Token.TokenResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Oauth2.Token.Token400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Oauth2.Token.Token401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Oauth2.Token.Token500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsTokenPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Oauth2.Token.TokenResponse?> PostAsync(global::LoliaFrpClient.Core.Oauth2.Token.TokenPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Oauth2.Token.TokenResponse> PostAsync(global::LoliaFrpClient.Core.Oauth2.Token.TokenPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Oauth2.Token.Token400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Oauth2.Token.Token401Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Oauth2.Token.Token500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Oauth2.Token.TokenResponse>(requestInfo, global::LoliaFrpClient.Core.Oauth2.Token.TokenResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 授权码流程第 3 步（服务端/客户端调用，无需用户登录态）。支持 grant_type：authorization_code（用授权码换令牌）与 refresh_token（刷新访问令牌）。请求体支持 application/x-www-form-urlencoded（推荐，RFC 标准）或 application/json，按 Content-Type 自动识别。客户端认证：仅支持在请求体中传 client_id + client_secret（client_secret_post），不支持 HTTP Basic（Authorization 头会被忽略）；public 客户端无需 client_secret。authorization_code：code 与 redirect_uri 必填，redirect_uri 须与 approve 时完全一致；授权码一次性、10 分钟有效；若授权时使用了 PKCE 则必须传 code_verifier（43~128 位 [A-Za-z0-9-._~]），public 客户端必须使用 PKCE。refresh_token：refresh_token 必填，会签发新 access_token 并使旧令牌失效，refresh_token 本身保持不变且过期时间不延长。被封禁用户无法换取/刷新令牌。所有响应均为 RFC 6749 风格：成功为标准令牌 JSON，失败为 {error, error_description}，均不使用 code/msg/data 包装。**鉴权**：OAuth2 客户端鉴权（client_id / client_secret）**错误响应**：| code | msg || --- | --- || 400 | invalid_request: 请求参数错误: &lt;校验错误详情&gt; || 401 | invalid_client: 无效的客户端ID || 401 | invalid_client: 应用已停用 || 401 | invalid_client: 客户端认证失败 || 400 | invalid_request: 缺少code或redirect_uri参数 || 400 | invalid_grant: 无效的授权码 || 400 | invalid_grant: 授权码已过期 || 400 | invalid_grant: 授权码已被使用 || 400 | invalid_grant: 授权码验证失败 || 400 | invalid_grant: public 客户端必须使用 PKCE || 400 | invalid_request: 缺少 code_verifier 参数 || 400 | invalid_grant: code_verifier 校验失败 || 400 | invalid_grant: PKCE 校验失败 || 400 | invalid_grant: 用户不可用 || 400 | invalid_request: 缺少refresh_token参数 || 400 | invalid_grant: 无效的刷新令牌 || 400 | invalid_grant: 刷新令牌已过期 || 400 | invalid_grant: 客户端ID不匹配 || 400 | unsupported_grant_type: 不支持的grant_type: &lt;grant_type&gt; || 500 | server_error: 内部错误 || 500 | server_error: 授权码处理失败 || 500 | server_error: 查询用户状态失败 || 500 | server_error: 生成令牌失败 || 500 | server_error: 创建令牌失败 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::LoliaFrpClient.Core.Oauth2.Token.TokenPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::LoliaFrpClient.Core.Oauth2.Token.TokenPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/x-www-form-urlencoded", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Oauth2.Token.TokenRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Core.Oauth2.Token.TokenRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Core.Oauth2.Token.TokenRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TokenRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
