// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace LoliaFrpClient.Core.Oauth2.Authorize
{
    /// <summary>客户端类型</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AuthorizeGetResponse_data_client_type
    {
        [EnumMember(Value = "confidential")]
        #pragma warning disable CS1591
        Confidential,
        #pragma warning restore CS1591
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        Public,
        #pragma warning restore CS1591
    }
}
