// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LoliaFrpClient.Core.User.Info
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InfoGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>头像 URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Avatar { get; set; }
#nullable restore
#else
        public string Avatar { get; set; }
#endif
        /// <summary>带宽限制（MB/s），0 表示不限速</summary>
        public int? BandwidthLimit { get; set; }
        /// <summary>注册时间（RFC3339）</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>邮箱</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>是否已完成实名认证</summary>
        public bool? HasKyc { get; set; }
        /// <summary>是否已绑定 QQ</summary>
        public bool? HasQq { get; set; }
        /// <summary>用户 ID</summary>
        public int? Id { get; set; }
        /// <summary>是否被封禁</summary>
        public bool? IsBanned { get; set; }
        /// <summary>剩余可用实名认证次数</summary>
        public int? KycCount { get; set; }
        /// <summary>实名认证记录状态：init / certifying / success / failed，无记录时为空字符串</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KycStatus { get; set; }
#nullable restore
#else
        public string KycStatus { get; set; }
#endif
        /// <summary>可创建隧道数量上限</summary>
        public int? MaxTunnelCount { get; set; }
        /// <summary>用户角色：user / sponsor / admin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif
        /// <summary>是否处于签到冷却期（距上次签到不足 24 小时，即当前不可签到）</summary>
        public bool? TodayChecked { get; set; }
        /// <summary>流量上限（字节）</summary>
        public int? TrafficLimit { get; set; }
        /// <summary>已使用流量（字节）</summary>
        public int? TrafficUsed { get; set; }
        /// <summary>用户名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.User.Info.InfoGetResponse_data"/> and sets the default values.
        /// </summary>
        public InfoGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.User.Info.InfoGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LoliaFrpClient.Core.User.Info.InfoGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LoliaFrpClient.Core.User.Info.InfoGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avatar", n => { Avatar = n.GetStringValue(); } },
                { "bandwidth_limit", n => { BandwidthLimit = n.GetIntValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "has_kyc", n => { HasKyc = n.GetBoolValue(); } },
                { "has_qq", n => { HasQq = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_banned", n => { IsBanned = n.GetBoolValue(); } },
                { "kyc_count", n => { KycCount = n.GetIntValue(); } },
                { "kyc_status", n => { KycStatus = n.GetStringValue(); } },
                { "max_tunnel_count", n => { MaxTunnelCount = n.GetIntValue(); } },
                { "role", n => { Role = n.GetStringValue(); } },
                { "today_checked", n => { TodayChecked = n.GetBoolValue(); } },
                { "traffic_limit", n => { TrafficLimit = n.GetIntValue(); } },
                { "traffic_used", n => { TrafficUsed = n.GetIntValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("avatar", Avatar);
            writer.WriteIntValue("bandwidth_limit", BandwidthLimit);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("email", Email);
            writer.WriteBoolValue("has_kyc", HasKyc);
            writer.WriteBoolValue("has_qq", HasQq);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_banned", IsBanned);
            writer.WriteIntValue("kyc_count", KycCount);
            writer.WriteStringValue("kyc_status", KycStatus);
            writer.WriteIntValue("max_tunnel_count", MaxTunnelCount);
            writer.WriteStringValue("role", Role);
            writer.WriteBoolValue("today_checked", TodayChecked);
            writer.WriteIntValue("traffic_limit", TrafficLimit);
            writer.WriteIntValue("traffic_used", TrafficUsed);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
