// <auto-generated/>
#pragma warning disable CS0618
using LoliaFrpClient.Core.User.Domain;
using LoliaFrpClient.Core.User.Frpc;
using LoliaFrpClient.Core.User.Info;
using LoliaFrpClient.Core.User.Nodes;
using LoliaFrpClient.Core.User.Oauth;
using LoliaFrpClient.Core.User.Traffic;
using LoliaFrpClient.Core.User.Tunnel;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LoliaFrpClient.Core.User
{
    /// <summary>
    /// Builds and executes requests for operations under \user
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The domain property</summary>
        public global::LoliaFrpClient.Core.User.Domain.DomainRequestBuilder Domain
        {
            get => new global::LoliaFrpClient.Core.User.Domain.DomainRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The frpc property</summary>
        public global::LoliaFrpClient.Core.User.Frpc.FrpcRequestBuilder Frpc
        {
            get => new global::LoliaFrpClient.Core.User.Frpc.FrpcRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The info property</summary>
        public global::LoliaFrpClient.Core.User.Info.InfoRequestBuilder Info
        {
            get => new global::LoliaFrpClient.Core.User.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The nodes property</summary>
        public global::LoliaFrpClient.Core.User.Nodes.NodesRequestBuilder Nodes
        {
            get => new global::LoliaFrpClient.Core.User.Nodes.NodesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::LoliaFrpClient.Core.User.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::LoliaFrpClient.Core.User.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The traffic property</summary>
        public global::LoliaFrpClient.Core.User.Traffic.TrafficRequestBuilder Traffic
        {
            get => new global::LoliaFrpClient.Core.User.Traffic.TrafficRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tunnel property</summary>
        public global::LoliaFrpClient.Core.User.Tunnel.TunnelRequestBuilder Tunnel
        {
            get => new global::LoliaFrpClient.Core.User.Tunnel.TunnelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
