// <auto-generated/>
#pragma warning disable CS0618
using LoliaFrpClient.Api.Node.Connect;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LoliaFrpClient.Api.Node
{
    /// <summary>
    /// Builds and executes requests for operations under \node
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NodeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The connect property</summary>
        public global::LoliaFrpClient.Api.Node.Connect.ConnectRequestBuilder Connect
        {
            get => new global::LoliaFrpClient.Api.Node.Connect.ConnectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Node.NodeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NodeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/node", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Node.NodeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NodeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/node", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
