// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Core.User.Oauth.Authorizations
{
    /// <summary>
    /// Builds and executes requests for operations under \user\oauth\authorizations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthorizationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthorizationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/oauth/authorizations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthorizationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/oauth/authorizations", rawUrl)
        {
        }
        /// <summary>
        /// 获取当前用户已授权（持有有效 OAuth2 令牌）的第三方应用列表，按 client_id 去重聚合；scope 取最近一次授权的权限范围。已删除的应用会被忽略。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | 此接口不支持OAuth2访问 || 500 | 获取授权列表失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsGetResponse?> GetAsAuthorizationsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsGetResponse> GetAsAuthorizationsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations403Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsGetResponse>(requestInfo, global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取当前用户已授权（持有有效 OAuth2 令牌）的第三方应用列表，按 client_id 去重聚合；scope 取最近一次授权的权限范围。已删除的应用会被忽略。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | 此接口不支持OAuth2访问 || 500 | 获取授权列表失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations503Error">When receiving a 503 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsAuthorizationsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations403Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Core.User.Oauth.Authorizations.Authorizations503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsResponse>(requestInfo, global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取当前用户已授权（持有有效 OAuth2 令牌）的第三方应用列表，按 client_id 去重聚合；scope 取最近一次授权的权限范围。已删除的应用会被忽略。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | 此接口不支持OAuth2访问 || 500 | 获取授权列表失败 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Core.User.Oauth.Authorizations.AuthorizationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AuthorizationsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
