// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LoliaFrpClient.Core.Admin.Tunnel.Item.Probe.Runs
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RunsGetResponse_data_items : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>执行探测的探针ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgentId { get; set; }
#nullable restore
#else
        public string AgentId { get; set; }
#endif
        /// <summary>记录创建时间</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>耗时（毫秒）</summary>
        public int? DurationMs { get; set; }
        /// <summary>探测记录ID</summary>
        public int? Id { get; set; }
        /// <summary>节点ID</summary>
        public int? NodeId { get; set; }
        /// <summary>探测结果列表（探针原样提交的 JSON，为空时返回 []）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Probe.Runs.RunsGetResponse_data_items_results>? Results { get; set; }
#nullable restore
#else
        public List<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Probe.Runs.RunsGetResponse_data_items_results> Results { get; set; }
#endif
        /// <summary>开始时间</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartedAt { get; set; }
#nullable restore
#else
        public string StartedAt { get; set; }
#endif
        /// <summary>探测目标地址</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Target { get; set; }
#nullable restore
#else
        public string Target { get; set; }
#endif
        /// <summary>目标ID</summary>
        public int? TargetId { get; set; }
        /// <summary>任务ID</summary>
        public int? TaskId { get; set; }
        /// <summary>隧道ID</summary>
        public int? TunnelId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Probe.Runs.RunsGetResponse_data_items"/> and sets the default values.
        /// </summary>
        public RunsGetResponse_data_items()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.Tunnel.Item.Probe.Runs.RunsGetResponse_data_items"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LoliaFrpClient.Core.Admin.Tunnel.Item.Probe.Runs.RunsGetResponse_data_items CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LoliaFrpClient.Core.Admin.Tunnel.Item.Probe.Runs.RunsGetResponse_data_items();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_id", n => { AgentId = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "duration_ms", n => { DurationMs = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "node_id", n => { NodeId = n.GetIntValue(); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Probe.Runs.RunsGetResponse_data_items_results>(global::LoliaFrpClient.Core.Admin.Tunnel.Item.Probe.Runs.RunsGetResponse_data_items_results.CreateFromDiscriminatorValue)?.AsList(); } },
                { "started_at", n => { StartedAt = n.GetStringValue(); } },
                { "target", n => { Target = n.GetStringValue(); } },
                { "target_id", n => { TargetId = n.GetIntValue(); } },
                { "task_id", n => { TaskId = n.GetIntValue(); } },
                { "tunnel_id", n => { TunnelId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("agent_id", AgentId);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteIntValue("duration_ms", DurationMs);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("node_id", NodeId);
            writer.WriteCollectionOfObjectValues<global::LoliaFrpClient.Core.Admin.Tunnel.Item.Probe.Runs.RunsGetResponse_data_items_results>("results", Results);
            writer.WriteStringValue("started_at", StartedAt);
            writer.WriteStringValue("target", Target);
            writer.WriteIntValue("target_id", TargetId);
            writer.WriteIntValue("task_id", TaskId);
            writer.WriteIntValue("tunnel_id", TunnelId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
