// <auto-generated/>
#pragma warning disable CS0618
using LoliaFrpClient.Api.User.Announcements.Board;
using LoliaFrpClient.Api.User.Announcements.Modal;
using LoliaFrpClient.Api.User.Announcements.Top;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Api.User.Announcements
{
    /// <summary>
    /// Builds and executes requests for operations under \user\announcements
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnnouncementsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The board property</summary>
        public global::LoliaFrpClient.Api.User.Announcements.Board.BoardRequestBuilder Board
        {
            get => new global::LoliaFrpClient.Api.User.Announcements.Board.BoardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The modal property</summary>
        public global::LoliaFrpClient.Api.User.Announcements.Modal.ModalRequestBuilder Modal
        {
            get => new global::LoliaFrpClient.Api.User.Announcements.Modal.ModalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The top property</summary>
        public global::LoliaFrpClient.Api.User.Announcements.Top.TopRequestBuilder Top
        {
            get => new global::LoliaFrpClient.Api.User.Announcements.Top.TopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.User.Announcements.AnnouncementsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnnouncementsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/announcements", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.User.Announcements.AnnouncementsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnnouncementsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/announcements", rawUrl)
        {
        }
        /// <summary>
        /// 获取所有公告（包含 top 与 board 两种显示位置）。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `announcement:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | OAuth2权限不足，需要以下权限之一: announcement:read || 500 | 获取公告失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Announcements.AnnouncementsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.User.Announcements.Announcements401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Announcements.Announcements403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Announcements.Announcements500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Announcements.Announcements503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.User.Announcements.AnnouncementsGetResponse?> GetAsAnnouncementsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.User.Announcements.AnnouncementsGetResponse> GetAsAnnouncementsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Api.User.Announcements.Announcements401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.User.Announcements.Announcements403Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.User.Announcements.Announcements500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Api.User.Announcements.Announcements503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.User.Announcements.AnnouncementsGetResponse>(requestInfo, global::LoliaFrpClient.Api.User.Announcements.AnnouncementsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取所有公告（包含 top 与 board 两种显示位置）。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `announcement:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | OAuth2权限不足，需要以下权限之一: announcement:read || 500 | 获取公告失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Announcements.AnnouncementsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.User.Announcements.Announcements401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Announcements.Announcements403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Announcements.Announcements500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Announcements.Announcements503Error">When receiving a 503 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsAnnouncementsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.User.Announcements.AnnouncementsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.User.Announcements.AnnouncementsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Api.User.Announcements.Announcements401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.User.Announcements.Announcements403Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.User.Announcements.Announcements500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Api.User.Announcements.Announcements503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.User.Announcements.AnnouncementsResponse>(requestInfo, global::LoliaFrpClient.Api.User.Announcements.AnnouncementsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取所有公告（包含 top 与 board 两种显示位置）。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `announcement:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | OAuth2权限不足，需要以下权限之一: announcement:read || 500 | 获取公告失败 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Announcements.AnnouncementsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Api.User.Announcements.AnnouncementsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Api.User.Announcements.AnnouncementsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AnnouncementsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
