// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\tunnel\{tunnel_id}\probe\latest
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LatestRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LatestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/tunnel/{tunnel_id}/probe/latest", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LatestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/tunnel/{tunnel_id}/probe/latest", rawUrl)
        {
        }
        /// <summary>
        /// 返回指定隧道最近一次探测记录（按 started_at 倒序）。无探测记录时仍返回 200，msg 为“暂无探测结果”，latest 为 null。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 隧道ID格式错误 || 404 | 隧道不存在 || 500 | 获取隧道信息失败 || 500 | 获取探测结果失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestGetResponse?> GetAsLatestGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestGetResponse> GetAsLatestGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestGetResponse>(requestInfo, global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 返回指定隧道最近一次探测记录（按 started_at 倒序）。无探测记录时仍返回 200，msg 为“暂无探测结果”，latest 为 null。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 隧道ID格式错误 || 404 | 隧道不存在 || 500 | 获取隧道信息失败 || 500 | 获取探测结果失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsLatestGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.Latest500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestResponse>(requestInfo, global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 返回指定隧道最近一次探测记录（按 started_at 倒序）。无探测记录时仍返回 200，msg 为“暂无探测结果”，latest 为 null。**鉴权**：需要管理员 JWT**OAuth2**：不允许使用 OAuth2 Access Token 调用**错误响应**：| code | msg || --- | --- || 400 | 隧道ID格式错误 || 404 | 隧道不存在 || 500 | 获取隧道信息失败 || 500 | 获取探测结果失败 || 401 | authorization header is missing || 401 | invalid token || 401 | access token expired || 403 | admin role required || 403 | 此接口不支持OAuth2访问 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Api.Admin.Tunnel.Item.Probe.Latest.LatestRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LatestRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
