// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LoliaFrpClient.Core.User.Traffic.Charges
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChargesGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>扣费明细列表</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LoliaFrpClient.Core.User.Traffic.Charges.ChargesGetResponse_data_charges>? Charges { get; set; }
#nullable restore
#else
        public List<global::LoliaFrpClient.Core.User.Traffic.Charges.ChargesGetResponse_data_charges> Charges { get; set; }
#endif
        /// <summary>实际统计天数</summary>
        public int? Days { get; set; }
        /// <summary>统计结束时间（RFC3339）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndTime { get; set; }
#nullable restore
#else
        public string EndTime { get; set; }
#endif
        /// <summary>每页数量</summary>
        public int? Limit { get; set; }
        /// <summary>当前页码</summary>
        public int? Page { get; set; }
        /// <summary>统计开始时间（RFC3339）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartTime { get; set; }
#nullable restore
#else
        public string StartTime { get; set; }
#endif
        /// <summary>明细总条数（仅 page=1 返回）</summary>
        public int? Total { get; set; }
        /// <summary>实际扣费合计（字节，仅 page=1 返回）</summary>
        public int? TotalCharged { get; set; }
        /// <summary>原始流量合计（字节，仅 page=1 返回）</summary>
        public int? TotalTraffic { get; set; }
        /// <summary>用户 ID（字符串形式）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.User.Traffic.Charges.ChargesGetResponse_data"/> and sets the default values.
        /// </summary>
        public ChargesGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.User.Traffic.Charges.ChargesGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LoliaFrpClient.Core.User.Traffic.Charges.ChargesGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LoliaFrpClient.Core.User.Traffic.Charges.ChargesGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "charges", n => { Charges = n.GetCollectionOfObjectValues<global::LoliaFrpClient.Core.User.Traffic.Charges.ChargesGetResponse_data_charges>(global::LoliaFrpClient.Core.User.Traffic.Charges.ChargesGetResponse_data_charges.CreateFromDiscriminatorValue)?.AsList(); } },
                { "days", n => { Days = n.GetIntValue(); } },
                { "end_time", n => { EndTime = n.GetStringValue(); } },
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "start_time", n => { StartTime = n.GetStringValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
                { "total_charged", n => { TotalCharged = n.GetIntValue(); } },
                { "total_traffic", n => { TotalTraffic = n.GetIntValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::LoliaFrpClient.Core.User.Traffic.Charges.ChargesGetResponse_data_charges>("charges", Charges);
            writer.WriteIntValue("days", Days);
            writer.WriteStringValue("end_time", EndTime);
            writer.WriteIntValue("limit", Limit);
            writer.WriteIntValue("page", Page);
            writer.WriteStringValue("start_time", StartTime);
            writer.WriteIntValue("total", Total);
            writer.WriteIntValue("total_charged", TotalCharged);
            writer.WriteIntValue("total_traffic", TotalTraffic);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
