// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace LoliaFrpClient.Api.Admin.Announcements.Item
{
    /// <summary>等级：info / warning / error / success / normal</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithAnnouncement_PutRequestBody_level
    {
        [EnumMember(Value = "info")]
        #pragma warning disable CS1591
        Info,
        #pragma warning restore CS1591
        [EnumMember(Value = "warning")]
        #pragma warning disable CS1591
        Warning,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "success")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
        [EnumMember(Value = "normal")]
        #pragma warning disable CS1591
        Normal,
        #pragma warning restore CS1591
    }
}
