// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Core.User.Domain.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \user\domain\{domain_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDomain_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDomain_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/domain/{domain_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDomain_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/domain/{domain_id}", rawUrl)
        {
        }
        /// <summary>
        /// 从白名单删除域名。若有隧道正在使用该域名（自定义域名等于该域名或其子域名），需先修改或删除相关隧道，否则返回 400。成功时无 data 字段。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `domain:write`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: domain:write || 400 | 无效的域名ID || 400 | 域名记录不存在 || 400 | 无权删除此域名 || 400 | 该域名正在被隧道使用，请先修改或删除相关隧道：&lt;隧道名(域名)&gt; |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_DeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_403Error">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_DeleteResponse?> DeleteAsWithDomain_DeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_DeleteResponse> DeleteAsWithDomain_DeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_403Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_DeleteResponse>(requestInfo, global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_DeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 从白名单删除域名。若有隧道正在使用该域名（自定义域名等于该域名或其子域名），需先修改或删除相关隧道，否则返回 400。成功时无 data 字段。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `domain:write`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: domain:write || 400 | 无效的域名ID || 400 | 域名记录不存在 || 400 | 无权删除此域名 || 400 | 该域名正在被隧道使用，请先修改或删除相关隧道：&lt;隧道名(域名)&gt; |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_403Error">When receiving a 403 status code</exception>
        [Obsolete("This method is obsolete. Use DeleteAsWithDomain_DeleteResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_Response?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_Response> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_403Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_Response>(requestInfo, global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 从白名单删除域名。若有隧道正在使用该域名（自定义域名等于该域名或其子域名），需先修改或删除相关隧道，否则返回 400。成功时无 data 字段。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `domain:write`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: domain:write || 400 | 无效的域名ID || 400 | 域名记录不存在 || 400 | 无权删除此域名 || 400 | 该域名正在被隧道使用，请先修改或删除相关隧道：&lt;隧道名(域名)&gt; |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Core.User.Domain.Item.WithDomain_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithDomain_ItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
