// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Core.Admin.Announcements.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\announcements\{announcement_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAnnouncement_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAnnouncement_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/announcements/{announcement_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAnnouncement_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/announcements/{announcement_id}", rawUrl)
        {
        }
        /// <summary>
        /// 软删除公告。**鉴权**：需要管理员 JWT（Authorization: Bearer &lt;token&gt;），不支持 OAuth2 Token**错误响应**：| code | msg || --- | --- || 400 | 公告 ID 无效 || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | role information not found || 403 | admin role required || 403 | 此接口不支持OAuth2访问 || 404 | 公告不存在 || 500 | 删除公告失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_DeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_DeleteResponse?> DeleteAsWithAnnouncement_DeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_DeleteResponse> DeleteAsWithAnnouncement_DeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_DeleteResponse>(requestInfo, global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_DeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 软删除公告。**鉴权**：需要管理员 JWT（Authorization: Bearer &lt;token&gt;），不支持 OAuth2 Token**错误响应**：| code | msg || --- | --- || 400 | 公告 ID 无效 || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | role information not found || 403 | admin role required || 403 | 此接口不支持OAuth2访问 || 404 | 公告不存在 || 500 | 删除公告失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_503Error">When receiving a 503 status code</exception>
        [Obsolete("This method is obsolete. Use DeleteAsWithAnnouncement_DeleteResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_Response?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_Response> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_Response>(requestInfo, global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 全量更新公告（所有字段都会被覆盖）。**鉴权**：需要管理员 JWT（Authorization: Bearer &lt;token&gt;），不支持 OAuth2 Token**错误响应**：| code | msg || --- | --- || 400 | 公告 ID 无效 || 400 | 请求参数错误 || 400 | 标题不能为空且最多 120 字符 || 400 | 内容不能为空且最多 5000 字符 || 400 | 公告等级无效 || 400 | 显示位置只能是 top 或 board || 400 | 按钮文字或链接过长 || 400 | 按钮文字和链接需要同时填写 || 400 | 按钮链接必须是有效的 HTTP 或 HTTPS 地址 || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | role information not found || 403 | admin role required || 403 | 此接口不支持OAuth2访问 || 404 | 公告不存在 || 500 | 更新公告失败 || 500 | 读取公告失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_PutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_PutResponse?> PutAsWithAnnouncement_PutResponseAsync(global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_PutResponse> PutAsWithAnnouncement_PutResponseAsync(global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_PutResponse>(requestInfo, global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_PutResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 全量更新公告（所有字段都会被覆盖）。**鉴权**：需要管理员 JWT（Authorization: Bearer &lt;token&gt;），不支持 OAuth2 Token**错误响应**：| code | msg || --- | --- || 400 | 公告 ID 无效 || 400 | 请求参数错误 || 400 | 标题不能为空且最多 120 字符 || 400 | 内容不能为空且最多 5000 字符 || 400 | 公告等级无效 || 400 | 显示位置只能是 top 或 board || 400 | 按钮文字或链接过长 || 400 | 按钮文字和链接需要同时填写 || 400 | 按钮链接必须是有效的 HTTP 或 HTTPS 地址 || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | role information not found || 403 | admin role required || 403 | 此接口不支持OAuth2访问 || 404 | 公告不存在 || 500 | 更新公告失败 || 500 | 读取公告失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_503Error">When receiving a 503 status code</exception>
        [Obsolete("This method is obsolete. Use PutAsWithAnnouncement_PutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_Response?> PutAsync(global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_Response> PutAsync(global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_Response>(requestInfo, global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 软删除公告。**鉴权**：需要管理员 JWT（Authorization: Bearer &lt;token&gt;），不支持 OAuth2 Token**错误响应**：| code | msg || --- | --- || 400 | 公告 ID 无效 || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | role information not found || 403 | admin role required || 403 | 此接口不支持OAuth2访问 || 404 | 公告不存在 || 500 | 删除公告失败 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// 全量更新公告（所有字段都会被覆盖）。**鉴权**：需要管理员 JWT（Authorization: Bearer &lt;token&gt;），不支持 OAuth2 Token**错误响应**：| code | msg || --- | --- || 400 | 公告 ID 无效 || 400 | 请求参数错误 || 400 | 标题不能为空且最多 120 字符 || 400 | 内容不能为空且最多 5000 字符 || 400 | 公告等级无效 || 400 | 显示位置只能是 top 或 board || 400 | 按钮文字或链接过长 || 400 | 按钮文字和链接需要同时填写 || 400 | 按钮链接必须是有效的 HTTP 或 HTTPS 地址 || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | role information not found || 403 | admin role required || 403 | 此接口不支持OAuth2访问 || 404 | 公告不存在 || 500 | 更新公告失败 || 500 | 读取公告失败 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Core.Admin.Announcements.Item.WithAnnouncement_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithAnnouncement_ItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithAnnouncement_ItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
