// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LoliaFrpClient.Api.User.Passkey.Login.Begin
{
    /// <summary>
    /// WebAuthn 选项（go-webauthn 生成），直接传给 navigator.credentials.get({ publicKey })，其中二进制字段为 base64url 编码
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BeginPostResponse_data_publicKey : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>允许的凭据（可发现登录通常为空/省略）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LoliaFrpClient.Api.User.Passkey.Login.Begin.BeginPostResponse_data_publicKey_allowCredentials>? AllowCredentials { get; set; }
#nullable restore
#else
        public List<global::LoliaFrpClient.Api.User.Passkey.Login.Begin.BeginPostResponse_data_publicKey_allowCredentials> AllowCredentials { get; set; }
#endif
        /// <summary>挑战值（base64url）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Challenge { get; set; }
#nullable restore
#else
        public string Challenge { get; set; }
#endif
        /// <summary>RP ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RpId { get; set; }
#nullable restore
#else
        public string RpId { get; set; }
#endif
        /// <summary>超时时间（毫秒）</summary>
        public int? Timeout { get; set; }
        /// <summary>用户验证要求，required</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserVerification { get; set; }
#nullable restore
#else
        public string UserVerification { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.User.Passkey.Login.Begin.BeginPostResponse_data_publicKey"/> and sets the default values.
        /// </summary>
        public BeginPostResponse_data_publicKey()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Passkey.Login.Begin.BeginPostResponse_data_publicKey"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LoliaFrpClient.Api.User.Passkey.Login.Begin.BeginPostResponse_data_publicKey CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LoliaFrpClient.Api.User.Passkey.Login.Begin.BeginPostResponse_data_publicKey();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowCredentials", n => { AllowCredentials = n.GetCollectionOfObjectValues<global::LoliaFrpClient.Api.User.Passkey.Login.Begin.BeginPostResponse_data_publicKey_allowCredentials>(global::LoliaFrpClient.Api.User.Passkey.Login.Begin.BeginPostResponse_data_publicKey_allowCredentials.CreateFromDiscriminatorValue)?.AsList(); } },
                { "challenge", n => { Challenge = n.GetStringValue(); } },
                { "rpId", n => { RpId = n.GetStringValue(); } },
                { "timeout", n => { Timeout = n.GetIntValue(); } },
                { "userVerification", n => { UserVerification = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::LoliaFrpClient.Api.User.Passkey.Login.Begin.BeginPostResponse_data_publicKey_allowCredentials>("allowCredentials", AllowCredentials);
            writer.WriteStringValue("challenge", Challenge);
            writer.WriteStringValue("rpId", RpId);
            writer.WriteIntValue("timeout", Timeout);
            writer.WriteStringValue("userVerification", UserVerification);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
