// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Core.User.Nodes
{
    /// <summary>
    /// Builds and executes requests for operations under \user\nodes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NodesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.User.Nodes.NodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NodesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/nodes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Core.User.Nodes.NodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NodesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/nodes", rawUrl)
        {
        }
        /// <summary>
        /// 分页获取可用节点列表（不含敏感信息）。注意：该接口为 POST，且必须携带 JSON 请求体（至少为 {}），空请求体会返回 400。load 为综合负载百分比（带宽 50%、CPU 20%、内存 10%、连接数 20% 加权），节点无系统信息上报时不返回该字段。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `node:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: node:read || 400 | 请求参数错误 || 500 | 获取节点列表失败 || 500 | 获取节点系统信息失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.User.Nodes.NodesPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.User.Nodes.Nodes400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Nodes.Nodes401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Nodes.Nodes403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Nodes.Nodes500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.User.Nodes.NodesPostResponse?> PostAsNodesPostResponseAsync(global::LoliaFrpClient.Core.User.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.User.Nodes.NodesPostResponse> PostAsNodesPostResponseAsync(global::LoliaFrpClient.Core.User.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.User.Nodes.Nodes400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.User.Nodes.Nodes401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.User.Nodes.Nodes403Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.User.Nodes.Nodes500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.User.Nodes.NodesPostResponse>(requestInfo, global::LoliaFrpClient.Core.User.Nodes.NodesPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 分页获取可用节点列表（不含敏感信息）。注意：该接口为 POST，且必须携带 JSON 请求体（至少为 {}），空请求体会返回 400。load 为综合负载百分比（带宽 50%、CPU 20%、内存 10%、连接数 20% 加权），节点无系统信息上报时不返回该字段。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `node:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: node:read || 400 | 请求参数错误 || 500 | 获取节点列表失败 || 500 | 获取节点系统信息失败 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.User.Nodes.NodesResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Core.User.Nodes.Nodes400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Nodes.Nodes401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Nodes.Nodes403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Core.User.Nodes.Nodes500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsNodesPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Core.User.Nodes.NodesResponse?> PostAsync(global::LoliaFrpClient.Core.User.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Core.User.Nodes.NodesResponse> PostAsync(global::LoliaFrpClient.Core.User.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LoliaFrpClient.Core.User.Nodes.Nodes400Error.CreateFromDiscriminatorValue },
                { "401", global::LoliaFrpClient.Core.User.Nodes.Nodes401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Core.User.Nodes.Nodes403Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Core.User.Nodes.Nodes500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Core.User.Nodes.NodesResponse>(requestInfo, global::LoliaFrpClient.Core.User.Nodes.NodesResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 分页获取可用节点列表（不含敏感信息）。注意：该接口为 POST，且必须携带 JSON 请求体（至少为 {}），空请求体会返回 400。load 为综合负载百分比（带宽 50%、CPU 20%、内存 10%、连接数 20% 加权），节点无系统信息上报时不返回该字段。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `node:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | invalid token || 403 | OAuth2权限不足，需要以下权限之一: node:read || 400 | 请求参数错误 || 500 | 获取节点列表失败 || 500 | 获取节点系统信息失败 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::LoliaFrpClient.Core.User.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::LoliaFrpClient.Core.User.Nodes.NodesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Core.User.Nodes.NodesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Core.User.Nodes.NodesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Core.User.Nodes.NodesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NodesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
