// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace LoliaFrpClient.Api.User.Kyc.Init
{
    /// <summary>证件类型：IDENTITY_CARD 身份证 / HOME_VISIT_PERMIT_HK_MC 港澳居民来往内地通行证 / HOME_VISIT_PERMIT_TAIWAN 台湾居民来往大陆通行证 / RESIDENCE_PERMIT_HK_MC 港澳居民居住证 / RESIDENCE_PERMIT_TAIWAN 台湾居民居住证 / PERMANENT_RESIDENCE_FOREIGNER 外国人永久居留证</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InitPostRequestBody_cert_type
    {
        [EnumMember(Value = "IDENTITY_CARD")]
        #pragma warning disable CS1591
        IDENTITY_CARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "HOME_VISIT_PERMIT_HK_MC")]
        #pragma warning disable CS1591
        HOME_VISIT_PERMIT_HK_MC,
        #pragma warning restore CS1591
        [EnumMember(Value = "HOME_VISIT_PERMIT_TAIWAN")]
        #pragma warning disable CS1591
        HOME_VISIT_PERMIT_TAIWAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESIDENCE_PERMIT_HK_MC")]
        #pragma warning disable CS1591
        RESIDENCE_PERMIT_HK_MC,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESIDENCE_PERMIT_TAIWAN")]
        #pragma warning disable CS1591
        RESIDENCE_PERMIT_TAIWAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERMANENT_RESIDENCE_FOREIGNER")]
        #pragma warning disable CS1591
        PERMANENT_RESIDENCE_FOREIGNER,
        #pragma warning restore CS1591
    }
}
