// <auto-generated/>
#pragma warning disable CS0618
using LoliaFrpClient.Api.Admin.Probe.Targets;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LoliaFrpClient.Api.Admin.Probe
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\probe
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProbeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The targets property</summary>
        public global::LoliaFrpClient.Api.Admin.Probe.Targets.TargetsRequestBuilder Targets
        {
            get => new global::LoliaFrpClient.Api.Admin.Probe.Targets.TargetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Admin.Probe.ProbeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProbeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/probe", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Admin.Probe.ProbeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProbeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/probe", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
