// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace LoliaFrpClient.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReleaseDownloadSelectionError : ApiException, IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>与 HTTP 状态码一致</summary>
        public int? Code { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError.ReleaseDownloadSelectionError_data? DataEscaped { get; set; }
#nullable restore
#else
        public global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError.ReleaseDownloadSelectionError_data DataEscaped { get; set; }
#endif
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>提示信息</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Msg { get; set; }
#nullable restore
#else
        public string Msg { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError"/> and sets the default values.
        /// </summary>
        public ReleaseDownloadSelectionError()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetIntValue(); } },
                { "data", n => { DataEscaped = n.GetObjectValue<global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError.ReleaseDownloadSelectionError_data>(global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError.ReleaseDownloadSelectionError_data.CreateFromDiscriminatorValue); } },
                { "msg", n => { Msg = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("code", Code);
            writer.WriteObjectValue<global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError.ReleaseDownloadSelectionError_data>("data", DataEscaped);
            writer.WriteStringValue("msg", Msg);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember1"/>, <see cref="global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReleaseDownloadSelectionError_data : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember1? ReleaseDownloadSelectionErrorDataMember1 { get; set; }
#nullable restore
#else
            public global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember1 ReleaseDownloadSelectionErrorDataMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember2? ReleaseDownloadSelectionErrorDataMember2 { get; set; }
#nullable restore
#else
            public global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember2 ReleaseDownloadSelectionErrorDataMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError.ReleaseDownloadSelectionError_data"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError.ReleaseDownloadSelectionError_data CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError.ReleaseDownloadSelectionError_data();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ReleaseDownloadSelectionErrorDataMember1 = new global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ReleaseDownloadSelectionErrorDataMember2 = new global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ReleaseDownloadSelectionErrorDataMember1 != null)
                {
                    return ReleaseDownloadSelectionErrorDataMember1.GetFieldDeserializers();
                }
                else if(ReleaseDownloadSelectionErrorDataMember2 != null)
                {
                    return ReleaseDownloadSelectionErrorDataMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ReleaseDownloadSelectionErrorDataMember1 != null)
                {
                    writer.WriteObjectValue<global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember1>(null, ReleaseDownloadSelectionErrorDataMember1);
                }
                else if(ReleaseDownloadSelectionErrorDataMember2 != null)
                {
                    writer.WriteObjectValue<global::LoliaFrpClient.Api.Models.ReleaseDownloadSelectionError_dataMember2>(null, ReleaseDownloadSelectionErrorDataMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
