// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LoliaFrpClient.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReleaseDownload : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The arch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Arch { get; set; }
#nullable restore
#else
        public string Arch { get; set; }
#endif
        /// <summary>The asset_id property</summary>
        public long? AssetId { get; set; }
        /// <summary>The checksum property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Checksum { get; set; }
#nullable restore
#else
        public string Checksum { get; set; }
#endif
        /// <summary>S3 签名 URL 到期时间；direct 和 GitHub 镜像为 null</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The filename property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Filename { get; set; }
#nullable restore
#else
        public string Filename { get; set; }
#endif
        /// <summary>The os property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Os { get; set; }
#nullable restore
#else
        public string Os { get; set; }
#endif
        /// <summary>The release_id property</summary>
        public long? ReleaseId { get; set; }
        /// <summary>The size property</summary>
        public long? Size { get; set; }
        /// <summary>实际选定的下载源；数值 ID 规范化为十进制字符串</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The tag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>客户端应使用此地址下载文件；S3 为临时签名 URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The version_id property</summary>
        public long? VersionId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.Models.ReleaseDownload"/> and sets the default values.
        /// </summary>
        public ReleaseDownload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.Models.ReleaseDownload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LoliaFrpClient.Api.Models.ReleaseDownload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LoliaFrpClient.Api.Models.ReleaseDownload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "arch", n => { Arch = n.GetStringValue(); } },
                { "asset_id", n => { AssetId = n.GetLongValue(); } },
                { "checksum", n => { Checksum = n.GetStringValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "filename", n => { Filename = n.GetStringValue(); } },
                { "os", n => { Os = n.GetStringValue(); } },
                { "release_id", n => { ReleaseId = n.GetLongValue(); } },
                { "size", n => { Size = n.GetLongValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "version_id", n => { VersionId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("arch", Arch);
            writer.WriteLongValue("asset_id", AssetId);
            writer.WriteStringValue("checksum", Checksum);
            writer.WriteDateTimeOffsetValue("expires_at", ExpiresAt);
            writer.WriteStringValue("filename", Filename);
            writer.WriteStringValue("os", Os);
            writer.WriteLongValue("release_id", ReleaseId);
            writer.WriteLongValue("size", Size);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("tag", Tag);
            writer.WriteStringValue("url", Url);
            writer.WriteLongValue("version_id", VersionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
