// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LoliaFrpClient.Api.User.Info
{
    /// <summary>
    /// Builds and executes requests for operations under \user\info
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InfoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.User.Info.InfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InfoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/info", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LoliaFrpClient.Api.User.Info.InfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InfoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/info", rawUrl)
        {
        }
        /// <summary>
        /// 获取当前登录用户的详细信息，包括角色、配额、流量、实名与签到状态等。支持 OAuth2 访问（需 user:read 权限）。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `user:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | OAuth2权限不足，需要以下权限之一: user:read || 404 | 用户不存在 || 500 | 发生内部错误 || 500 | 用户ID类型错误 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Info.InfoGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.User.Info.Info401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Info.Info403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Info.Info404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Info.Info500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Info.Info503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.User.Info.InfoGetResponse?> GetAsInfoGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.User.Info.InfoGetResponse> GetAsInfoGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Api.User.Info.Info401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.User.Info.Info403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Api.User.Info.Info404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.User.Info.Info500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Api.User.Info.Info503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.User.Info.InfoGetResponse>(requestInfo, global::LoliaFrpClient.Api.User.Info.InfoGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取当前登录用户的详细信息，包括角色、配额、流量、实名与签到状态等。支持 OAuth2 访问（需 user:read 权限）。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `user:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | OAuth2权限不足，需要以下权限之一: user:read || 404 | 用户不存在 || 500 | 发生内部错误 || 500 | 用户ID类型错误 |
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Info.InfoResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LoliaFrpClient.Api.User.Info.Info401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Info.Info403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Info.Info404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Info.Info500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::LoliaFrpClient.Api.User.Info.Info503Error">When receiving a 503 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsInfoGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LoliaFrpClient.Api.User.Info.InfoResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LoliaFrpClient.Api.User.Info.InfoResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LoliaFrpClient.Api.User.Info.Info401Error.CreateFromDiscriminatorValue },
                { "403", global::LoliaFrpClient.Api.User.Info.Info403Error.CreateFromDiscriminatorValue },
                { "404", global::LoliaFrpClient.Api.User.Info.Info404Error.CreateFromDiscriminatorValue },
                { "500", global::LoliaFrpClient.Api.User.Info.Info500Error.CreateFromDiscriminatorValue },
                { "503", global::LoliaFrpClient.Api.User.Info.Info503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LoliaFrpClient.Api.User.Info.InfoResponse>(requestInfo, global::LoliaFrpClient.Api.User.Info.InfoResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取当前登录用户的详细信息，包括角色、配额、流量、实名与签到状态等。支持 OAuth2 访问（需 user:read 权限）。**鉴权**：需要用户 JWT（Authorization: Bearer &lt;token&gt;）**OAuth2**：支持 OAuth2 Access Token，需要 scope `user:read`**错误响应**：| code | msg || --- | --- || 401 | authorization header is missing || 401 | authorization header format must be Bearer {token} || 401 | invalid token || 401 | access token expired || 401 | token has been revoked || 503 | token validation temporarily unavailable || 403 | OAuth2权限不足，需要以下权限之一: user:read || 404 | 用户不存在 || 500 | 发生内部错误 || 500 | 用户ID类型错误 |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LoliaFrpClient.Api.User.Info.InfoRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LoliaFrpClient.Api.User.Info.InfoRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LoliaFrpClient.Api.User.Info.InfoRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InfoRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
